# Import libraries

### We'll see what these do later on

In [1]:
import os
import pandas as pd
import re
from bs4 import BeautifulSoup
import requests

# Request Response Cycle

In [2]:
# Its very important to understand the request response cycle 
# We want to scrap data from web, so we need to understand the basics of web 
# What happens if we google search about something, we get a webpage in return, right
# Its simple enough till this point but there's a lot that happens in the backend

# I'll explain in very simple words, so I might be a little off in my explaination
# But my intention here is to give an intuition about how internet works

# When we go to a website, we either get a webpage as an output on our screen
# Or we get an error (error 404 page does not exist)

# Simple enough, right? But there's a lot that happens in the backend though

# Let's understand a server first
# A server is just another computer owned by someone else, which is connected to internet
# And just because we're using windows on our machines
# doesn't mean, the other person is also using windows, right
# So we have web protocols like https
# https means hypertext transfer protocol secure
# www means world wide web
# https says we all should converse in the same language over the web
# lets take an example

# First let's say we go to https://www.google.com/search?q=apple

# We request the server "google.com" over the world wide web
# using the https protocol that
# We want to access your server and 
# we want to search apple over the web using your server

# The search?q=apple argument in the url means its a dictionary in an url format
# a dictionary is a data structure which has key:value pairs  
# key of the dictionary is "search", and the value is user defined 
# In our case the value is "apple"
# In python this dictionary would look like {"search":"apple"}

# So, we make a request over the world wide web
# that we want to access "google.com" server
# and using that server, we want to search the word "apple" using the
# https protocol

# Once our request is accepted by the server "google.com"
# It returns a response object first
# On the web, the response is usually written in html 
# So, we need to convert that response to html

# So, in a nutshell, this was request response cycle 
# We send a request and get a response in return

# A little extra info
# Character encoding: 
# People who use english, type characters in their keyboards like
# the letter from a to z, from capitalized A to Z
# the numerics 0-9
# and the special character like $ or !
# This is all a part of ascii
# You can google ascii for more info 
# But say a person who does not speak english
# how would he interpret these english letters?
# a japanese person use a keyboard with japanese letters
# So, we need a way to convert our english language to japanese in
# order to communicate with folks around the world who don't
# speak english

# In the same way, different machines have different
# characters that they can understand
# python works on I guess unicode
# But the world wide web has I guess utf-8 character encoding

# So, some times, we need to be careful to choose the right character encoding as well
# So, there are times we need to encode or decode our character encodings properly

# Our modern day browsers automate so much work behind the scenes, right :)

In [3]:
 
URL = 'https://www.flipkart.com/air-conditioners/pr?sid=j9e,abm,c54&p[]=facets.fulfilled_by%255B%255D%3DFlipkart%2BAssured&p[]=facets.technology%255B%255D%3DInverter&p[]=facets.serviceability%5B%5D%3Dtrue&otracker=categorytree&otracker=nmenu_sub_TVs%20%26%20Appliances_0_Inverter%20AC'

In [4]:
# Now that we have a url 
# lets understand request response cycle
# we will create a response object here using requests library

# requests.get will first send the request and later would return a response
page = requests.get(URL)
page

In [5]:
# page.content retrieves all the content from the response object
print(page.content[:100])

b'<!doctype html><html lang="en"><head><link href="https://rukminim1.flixcart.com" rel="preconnect"/><'

In [6]:
# page.text will retrive all html text data from the response
# I'll talk about the difference between .text and .content later
print(page.text[:500])

<!doctype html><html lang="en"><head><link href="https://rukminim1.flixcart.com" rel="preconnect"/><link rel="stylesheet" href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app_modules.chunk.905c37.css"/><link rel="stylesheet" href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app.chunk.104e9a.css"/><meta http-equiv="Content-type" content="text/html; charset=utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=Edge"/><meta property="fb:page_id" content

In [7]:
# Now that we have a response from the url
# we can proceed to parse it into html that we
# could read in python

soup = BeautifulSoup(page.content, "html.parser")
# this line means, we want all the contents of our response object
# html.parser means we want to read our response as html

In [8]:
page = requests.get(URL)

# Here we'll iterate over all the <a> tags in our parsed html which
# have class id: "_1fQZEK" and 
# which contains an external link (href=True)
for a in soup.find_all("a", href=True, attrs={"class":"_1fQZEK"}):
    name = a.find("div", attrs={"class":"_4rR01T"})
    # this a.find will find any <div> tag that has class id: "_4rR01T"
    print(name)

<div class="_4rR01T">Voltas 1.5 Ton 5 Star Split Inverter AC  - White</div>
<div class="_4rR01T">Voltas 1.5 Ton 3 Star Split Inverter AC  - White</div>
<div class="_4rR01T">MarQ by Flipkart Convertible 4-in-1 Cooling 1.5 Ton 3 Star Split Inverter AC  - White</div>
<div class="_4rR01T">SAMSUNG 1.5 Ton 5 Star Split Inverter AC  - White</div>
<div class="_4rR01T">Lloyd 1.5 Ton 5 Star Split Inverter AC  - White</div>
<div class="_4rR01T">Blue Star 0.8 Ton 3 Star Split Inverter AC  - White</div>
<div class="_4rR01T">Voltas 1.5 Ton 4 Star Split Inverter AC  - White</div>
<div class="_4rR01T">CARRIER Flexicool Convertible 4-in-1 Cooling 1.5 Ton 4 Star Split Inverter Dual Filtration with HD and...</div>
<div class="_4rR01T">Godrej 1.5 Ton 5 Star Split Inverter Convertible 5-in-1 Cooling With Anti-Virus Protection AC  - White...</div>
<div class="_4rR01T">Whirlpool 4 in 1 Convertible Cooling 1.5 Ton 3 Star Split Inverter AC  - White</div>
<div class="_4rR01T">Panasonic 1.5 Ton 5 Star Split Inverter AC with Wi-fi Connect  - White</div>
<div class="_4rR01T">Blue Star 1.5 Ton 3 Star Split Inverter AC  - White</div>
<div class="_4rR01T">Panasonic 1.5 Ton 3 Star Split Inverter AC with Wi-fi Connect  - White</div>
<div class="_4rR01T">Lloyd 1.2 Ton 3 Star Split Inverter AC  - White</div>
<div class="_4rR01T">CARRIER 1.5 Ton 5 Star Split Inverter AC  - White</div>
<div class="_4rR01T">CARRIER Flexicool Convertible 4-in-1 Cooling 1.2 Ton 5 Star Split Inverter Auto Cleanser, Dual Filtrat...</div>
<div class="_4rR01T">Panasonic 1 Ton 5 Star Split Inverter AC with Wi-fi Connect  - White</div>
<div class="_4rR01T">SAMSUNG Convertible 5-in-1 Cooling Mode 1.5 Ton 3 Star Split Inverter Anti Bacteria Filter AC  - White</div>
<div class="_4rR01T">realme TechLife 4-in-1 Convertible 1.5 Ton 4 Star Split Inverter , AC  - White</div>
<div class="_4rR01T">Blue Star Convertible 4-in-1 Cooling 1 Ton 5 Star Split Inverter AC  - White</div>
<div class="_4rR01T">Blue Star Convertible 4-in-1 Cooling 1.5 Ton 5 Star Split Inverter AC  - White</div>
<div class="_4rR01T">SAMSUNG Convertible 5-in-1 Cooling Mode 1.5 Ton 5 Star Split Inverter Anti Bacteria Filter AC  - White</div>
<div class="_4rR01T">Whirlpool 4 in 1 Convertible Cooling 1 Ton 5 Star Split Inverter AC  - White</div>
<div class="_4rR01T">Whirlpool 4 in 1 Convertible Cooling 1.5 Ton 3 Star Split Inverter AC  - White</div>

In [9]:
page = requests.get(URL)

for a in soup.find_all("a", href=True, attrs={"class":"_1fQZEK"}):
    name = a.find("div", attrs={"class":"_4rR01T"})
    print(name.text)

# Notice the difference if we print just name vs
# if we print name.text

Voltas 1.5 Ton 5 Star Split Inverter AC  - White
Voltas 1.5 Ton 3 Star Split Inverter AC  - White
MarQ by Flipkart Convertible 4-in-1 Cooling 1.5 Ton 3 Star Split Inverter AC  - White
SAMSUNG 1.5 Ton 5 Star Split Inverter AC  - White
Lloyd 1.5 Ton 5 Star Split Inverter AC  - White
Blue Star 0.8 Ton 3 Star Split Inverter AC  - White
Voltas 1.5 Ton 4 Star Split Inverter AC  - White
CARRIER Flexicool Convertible 4-in-1 Cooling 1.5 Ton 4 Star Split Inverter Dual Filtration with HD and...
Godrej 1.5 Ton 5 Star Split Inverter Convertible 5-in-1 Cooling With Anti-Virus Protection AC  - White...
Whirlpool 4 in 1 Convertible Cooling 1.5 Ton 3 Star Split Inverter AC  - White
Panasonic 1.5 Ton 5 Star Split Inverter AC with Wi-fi Connect  - White
Blue Star 1.5 Ton 3 Star Split Inverter AC  - White
Panasonic 1.5 Ton 3 Star Split Inverter AC with Wi-fi Connect  - White
Lloyd 1.2 Ton 3 Star Split Inverter AC  - White
CARRIER 1.5 Ton 5 Star Split Inverter AC  - White
CARRIER Flexicool Convertible 4-in-1 Cooling 1.2 Ton 5 Star Split Inverter Auto Cleanser, Dual Filtrat...
Panasonic 1 Ton 5 Star Split Inverter AC with Wi-fi Connect  - White
SAMSUNG Convertible 5-in-1 Cooling Mode 1.5 Ton 3 Star Split Inverter Anti Bacteria Filter AC  - White
realme TechLife 4-in-1 Convertible 1.5 Ton 4 Star Split Inverter , AC  - White
Blue Star Convertible 4-in-1 Cooling 1 Ton 5 Star Split Inverter AC  - White
Blue Star Convertible 4-in-1 Cooling 1.5 Ton 5 Star Split Inverter AC  - White
SAMSUNG Convertible 5-in-1 Cooling Mode 1.5 Ton 5 Star Split Inverter Anti Bacteria Filter AC  - White
Whirlpool 4 in 1 Convertible Cooling 1 Ton 5 Star Split Inverter AC  - White
Whirlpool 4 in 1 Convertible Cooling 1.5 Ton 3 Star Split Inverter AC  - White

In [10]:
page = requests.get(URL)

for a in soup.find_all("a", href=True, attrs={"class":"_1fQZEK"}):
    name = a.find("div", attrs={"class":"_4rR01T"})
    print(name.contents)

# Notice the difference if we print name.text vs
# if we print name.contents
# name.contents will give us not just text but it returns
# every element and stores those elements as a list
# In this case, we only had a single string
# So, the only difference name.text and name.contents made
# was that .text directly returns text
# while .contents returns a list

['Voltas 1.5 Ton 5 Star Split Inverter AC  - White']
['Voltas 1.5 Ton 3 Star Split Inverter AC  - White']
['MarQ by Flipkart Convertible 4-in-1 Cooling 1.5 Ton 3 Star Split Inverter AC  - White']
['SAMSUNG 1.5 Ton 5 Star Split Inverter AC  - White']
['Lloyd 1.5 Ton 5 Star Split Inverter AC  - White']
['Blue Star 0.8 Ton 3 Star Split Inverter AC  - White']
['Voltas 1.5 Ton 4 Star Split Inverter AC  - White']
['CARRIER Flexicool Convertible 4-in-1 Cooling 1.5 Ton 4 Star Split Inverter Dual Filtration with HD and...']
['Godrej 1.5 Ton 5 Star Split Inverter Convertible 5-in-1 Cooling With Anti-Virus Protection AC  - White...']
['Whirlpool 4 in 1 Convertible Cooling 1.5 Ton 3 Star Split Inverter AC  - White']
['Panasonic 1.5 Ton 5 Star Split Inverter AC with Wi-fi Connect  - White']
['Blue Star 1.5 Ton 3 Star Split Inverter AC  - White']
['Panasonic 1.5 Ton 3 Star Split Inverter AC with Wi-fi Connect  - White']
['Lloyd 1.2 Ton 3 Star Split Inverter AC  - White']
['CARRIER 1.5 Ton 5 Star Split Inverter AC  - White']
['CARRIER Flexicool Convertible 4-in-1 Cooling 1.2 Ton 5 Star Split Inverter Auto Cleanser, Dual Filtrat...']
['Panasonic 1 Ton 5 Star Split Inverter AC with Wi-fi Connect  - White']
['SAMSUNG Convertible 5-in-1 Cooling Mode 1.5 Ton 3 Star Split Inverter Anti Bacteria Filter AC  - White']
['realme TechLife 4-in-1 Convertible 1.5 Ton 4 Star Split Inverter , AC  - White']
['Blue Star Convertible 4-in-1 Cooling 1 Ton 5 Star Split Inverter AC  - White']
['Blue Star Convertible 4-in-1 Cooling 1.5 Ton 5 Star Split Inverter AC  - White']
['SAMSUNG Convertible 5-in-1 Cooling Mode 1.5 Ton 5 Star Split Inverter Anti Bacteria Filter AC  - White']
['Whirlpool 4 in 1 Convertible Cooling 1 Ton 5 Star Split Inverter AC  - White']
['Whirlpool 4 in 1 Convertible Cooling 1.5 Ton 3 Star Split Inverter AC  - White']

In [11]:
page = requests.get(URL)

for a in soup.find_all("a", href=True, attrs={"class":"_1fQZEK"}):
    name = a.find("div", attrs={"class":"_4rR01T"})
    price=a.find("div", attrs={"class":"_30jeq3 _1_WHN1"})
    print(price)

<div class="_30jeq3 _1_WHN1">₹37,499</div>
<div class="_30jeq3 _1_WHN1">₹32,990</div>
<div class="_30jeq3 _1_WHN1">₹28,499</div>
<div class="_30jeq3 _1_WHN1">₹39,999</div>
<div class="_30jeq3 _1_WHN1">₹36,999</div>
<div class="_30jeq3 _1_WHN1">₹27,999</div>
<div class="_30jeq3 _1_WHN1">₹34,990</div>
<div class="_30jeq3 _1_WHN1">₹38,499</div>
<div class="_30jeq3 _1_WHN1">₹36,960</div>
<div class="_30jeq3 _1_WHN1">₹31,490</div>
<div class="_30jeq3 _1_WHN1">₹43,990</div>
<div class="_30jeq3 _1_WHN1">₹35,490</div>
<div class="_30jeq3 _1_WHN1">₹37,990</div>
<div class="_30jeq3 _1_WHN1">₹30,980</div>
<div class="_30jeq3 _1_WHN1">₹39,999</div>
<div class="_30jeq3 _1_WHN1">₹37,999</div>
<div class="_30jeq3 _1_WHN1">₹36,490</div>
<div class="_30jeq3 _1_WHN1">₹33,999</div>
<div class="_30jeq3 _1_WHN1">₹29,999</div>
<div class="_30jeq3 _1_WHN1">₹36,990</div>
<div class="_30jeq3 _1_WHN1">₹42,999</div>
<div class="_30jeq3 _1_WHN1">₹37,999</div>
<div class="_30jeq3 _1_WHN1">₹34,990</div>
<div class="_30jeq3 _1_WHN1">₹32,990</div>

In [12]:
page = requests.get(URL)

for a in soup.find_all("a", href=True, attrs={"class":"_1fQZEK"}):
    name = a.find("div", attrs={"class":"_4rR01T"})
    price=a.find("div", attrs={"class":"_30jeq3 _1_WHN1"}).text
    print(price)

₹37,499
₹32,990
₹28,499
₹39,999
₹36,999
₹27,999
₹34,990
₹38,499
₹36,960
₹31,490
₹43,990
₹35,490
₹37,990
₹30,980
₹39,999
₹37,999
₹36,490
₹33,999
₹29,999
₹36,990
₹42,999
₹37,999
₹34,990
₹32,990

In [13]:
# Lets remove that weird currency character from our price
page = requests.get(URL)

for a in soup.find_all("a", href=True, attrs={"class":"_1fQZEK"}):
    name = a.find("div", attrs={"class":"_4rR01T"})
    price=a.find("div", attrs={"class":"_30jeq3 _1_WHN1"}).text
    price = price.encode("ascii", "ignore").decode("ascii")
    # first, we encode our text as ascii
    # if characters exists in ascii good, numerics and comma will qualify here
    # but the currency character will be ignored 
    # the we decode back to our unicode that python understands
    # don't worry if this doesn't make much sense
    # I'll later show a way better way of doing it
    print(price)

37,499
32,990
28,499
39,999
36,999
27,999
34,990
38,499
36,960
31,490
43,990
35,490
37,990
30,980
39,999
37,999
36,490
33,999
29,999
36,990
42,999
37,999
34,990
32,990

In [14]:
page = requests.get(URL)

soup = BeautifulSoup(page.content, "html.parser")

products = []
prices = []

for a in soup.find_all("a", href=True, attrs={"class":"_1fQZEK"}):
    name = a.find("div", attrs={"class":"_4rR01T"})
    price=a.find("div", attrs={"class":"_30jeq3 _1_WHN1"})
    products.append(name.text)                                                                                                                                       
    prices.append(price.text.encode("ascii", "ignore").decode("ascii"))

df = pd.DataFrame({"Product Name":products, "Price":prices})

df.head()

                                        Product Name   Price
0   Voltas 1.5 Ton 5 Star Split Inverter AC  - White  37,499
1   Voltas 1.5 Ton 3 Star Split Inverter AC  - White  32,990
2  MarQ by Flipkart Convertible 4-in-1 Cooling 1....  28,499
3  SAMSUNG 1.5 Ton 5 Star Split Inverter AC  - White  39,999
4    Lloyd 1.5 Ton 5 Star Split Inverter AC  - White  36,999

# Better way of parsing data and getting rid of unwanted characters

In [15]:
# Lets first understand the problem
# we have a price column which has a weird currency character in it
# because of which, we cant directly convert our price to integers
# As part of any analysis, we need to convert price from string to integers or floats
# Say, to find the minimum price, we can use minimum only on numeric data

# So, we need to pull our numeric digits out of the price string
# For that we'll use additional functionality known as
# Regular Expression
# import re # this is the module for regular expressions

In [16]:
import re

# Lets say we had a string out of which we need to pull out
# a numeric data
string1 = "@#$%$@#342523452435"

# First, lets see the re module
# We'll soon discuss the pattern to extract don't worry
pattern_to_extract = "[0-9]"

what_is_this_variable = re.findall(pattern_to_extract, string1)
print(what_is_this_variable)

['3', '4', '2', '5', '2', '3', '4', '5', '2', '4', '3', '5']

In [17]:
# first, we use re.findall to find a pattern in data
# the pattern found every numeric data and appended that
# indivisual numeric data to a list

# now that we have our numeric data lets convert it into integers
price_string = "".join(what_is_this_variable)
# this will join our list
print(price_string)

342523452435

In [18]:
# Now we convert this joined string to integer
price_integer = int(price_string)
print(price_integer)

342523452435

In [19]:
# Now, lets talk about the pattern we used to extract numerics
pattern = "[0-9]"
# this means, pull out numbers matching every digit between 0 to 9 
# [0-9] is a syntax of regular expressions
# we could also have used [0123456789] as a pattern
pattern2 = "[0123456789]"
print(re.findall(pattern2, string1))

['3', '4', '2', '5', '2', '3', '4', '5', '2', '4', '3', '5']

In [20]:
# To understand the pattern matching lets pull out the character
# a from a string " a b ac"
pattern_a = "[a]"
some_string = " a b ac"
print(re.findall(pattern_a, some_string))

# the output will be, find the pattern as many times it 
# occurs in our string

['a', 'a']

In [21]:
# Lets try another example
pattern_5 = "[5]"
some_string = "abs sda 555 666"

# We want to pull the digit 5 out of this string
print(re.findall(pattern_5, some_string))

['5', '5', '5']

In [22]:
# Now with pattern matching under our belt
# lets convert our dataframe price to integers

# But lets just do one more example first
# Lets convert this string to integer

pattern = "[0123456789]"
some_string = "$56,700,987"

answer = re.findall(pattern, some_string)

print("At this point our variable answer is a list \n", answer)
# the \n just introduce a new line in our console output
# So that our list would be printed in a new line
# So, \n is just a new line character which is not visible in output
print()
answer = "".join(answer)
print("Now our answer variable list has been converted to string \n", answer)
print()
answer = int(answer)
print("our answer variable must now be an integer, \n", answer)
print(type(answer))

At this point our variable answer is a list
 ['5', '6', '7', '0', '0', '9', '8', '7']

Now our answer variable list has been converted to string
 56700987

our answer variable must now be an integer,
 56700987
<class 'int'>

# Create our parsed dataframe
## This time we'll convert our price column to intergers'

### But now, we will not use encode and decode
    price.text.encode("ascii", "ignore").decode("ascii"))

In [23]:
page = requests.get(URL)

soup = BeautifulSoup(page.content, "html.parser")

products = []
prices = []

for a in soup.find_all("a", href=True, attrs={"class":"_1fQZEK"}):
    name = a.find("div", attrs={"class":"_4rR01T"})
    price=a.find("div", attrs={"class":"_30jeq3 _1_WHN1"})
    products.append(name.text)                                                                                                                                       
    prices.append(price.text)

df = pd.DataFrame({"Product Name":products, "Price":prices})

df.head()

                                        Product Name    Price
0   Voltas 1.5 Ton 5 Star Split Inverter AC  - White  ₹37,499
1   Voltas 1.5 Ton 3 Star Split Inverter AC  - White  ₹32,990
2  MarQ by Flipkart Convertible 4-in-1 Cooling 1....  ₹28,499
3  CARRIER Flexicool Convertible 6-in-1 Cooling 1...  ₹40,990
4    Lloyd 1.5 Ton 5 Star Split Inverter AC  - White  ₹36,999

In [24]:
# We will create a custom function which we will apply 
# row by row on price column of our dataframe
# so on each iteration, our function will convert the
# price in string format to integer format

# We use a default pattern here, which means
# if we don't specify pattern while using this function
# the default value of pattern argument will be "[0123456789]"
# some_string will assume price column string row by row
def convert_data_using_pattern(some_string, pattern="[0123456789]"):
    import re
    our_data = re.findall(pattern, some_string)
    our_data = "".join(our_data)
    our_data = int(our_data)
    return our_data

In [25]:
df["Price"]

0     ₹37,499
1     ₹32,990
2     ₹28,499
3     ₹40,990
4     ₹36,999
5     ₹27,999
6     ₹34,990
7     ₹39,999
8     ₹36,960
9     ₹31,490
10    ₹43,990
11    ₹35,490
12    ₹37,990
13    ₹30,980
14    ₹39,999
15    ₹37,999
16    ₹38,499
17    ₹36,490
18    ₹29,999
19    ₹36,990
20    ₹33,999
21    ₹51,999
22    ₹34,990
23    ₹32,990
Name: Price, dtype: object

In [26]:
df["Price"].apply(
        lambda column_price: convert_data_using_pattern(column_price)
    )

0     37499
1     32990
2     28499
3     40990
4     36999
5     27999
6     34990
7     39999
8     36960
9     31490
10    43990
11    35490
12    37990
13    30980
14    39999
15    37999
16    38499
17    36490
18    29999
19    36990
20    33999
21    51999
22    34990
23    32990
Name: Price, dtype: int64

In [27]:
# Notice the dtpye: int64 in console output

In [28]:
df["Price"] = df["Price"].apply(
    lambda column_price: convert_data_using_pattern(column_price))

In [29]:
df

                                         Product Name  Price
0    Voltas 1.5 Ton 5 Star Split Inverter AC  - White  37499
1    Voltas 1.5 Ton 3 Star Split Inverter AC  - White  32990
2   MarQ by Flipkart Convertible 4-in-1 Cooling 1....  28499
3   CARRIER Flexicool Convertible 6-in-1 Cooling 1...  40990
4     Lloyd 1.5 Ton 5 Star Split Inverter AC  - White  36999
5   Blue Star 0.8 Ton 3 Star Split Inverter AC  - ...  27999
6    Voltas 1.5 Ton 4 Star Split Inverter AC  - White  34990
7   SAMSUNG 1.5 Ton 5 Star Split Inverter AC  - White  39999
8   Godrej 1.5 Ton 5 Star Split Inverter Convertib...  36960
9   Whirlpool 4 in 1 Convertible Cooling 1.5 Ton 3...  31490
10  Panasonic 1.5 Ton 5 Star Split Inverter AC wit...  43990
11  Blue Star 1.5 Ton 3 Star Split Inverter AC  - ...  35490
12  Panasonic 1.5 Ton 3 Star Split Inverter AC wit...  37990
13    Lloyd 1.2 Ton 3 Star Split Inverter AC  - White  30980
14  CARRIER 1.5 Ton 5 Star Split Inverter AC  - White  39999
15  CARRIER Flexicool Convertible 4-in-1 Cooling 1...  37999
16  CARRIER Flexicool Convertible 4-in-1 Cooling 1...  38499
17  Panasonic 1 Ton 5 Star Split Inverter AC with ...  36490
18  realme TechLife 4-in-1 Convertible 1.5 Ton 4 S...  29999
19  Blue Star Convertible 4-in-1 Cooling 1 Ton 5 S...  36990
20  SAMSUNG Convertible 5-in-1 Cooling Mode 1.5 To...  33999
21  CARRIER Flexicool Convertible 4-in-1 Cooling 2...  51999
22  Whirlpool 4 in 1 Convertible Cooling 1 Ton 5 S...  34990
23  Whirlpool 4 in 1 Convertible Cooling 1.5 Ton 3...  32990

In [30]:
# Notice, even the comma was removed now

In [31]:
print(df.dtypes)

Product Name    object
Price            int64
dtype: object

In [32]:
df.sort_values(by="Price", ascending=True)

                                         Product Name  Price
5   Blue Star 0.8 Ton 3 Star Split Inverter AC  - ...  27999
2   MarQ by Flipkart Convertible 4-in-1 Cooling 1....  28499
18  realme TechLife 4-in-1 Convertible 1.5 Ton 4 S...  29999
13    Lloyd 1.2 Ton 3 Star Split Inverter AC  - White  30980
9   Whirlpool 4 in 1 Convertible Cooling 1.5 Ton 3...  31490
23  Whirlpool 4 in 1 Convertible Cooling 1.5 Ton 3...  32990
1    Voltas 1.5 Ton 3 Star Split Inverter AC  - White  32990
20  SAMSUNG Convertible 5-in-1 Cooling Mode 1.5 To...  33999
6    Voltas 1.5 Ton 4 Star Split Inverter AC  - White  34990
22  Whirlpool 4 in 1 Convertible Cooling 1 Ton 5 S...  34990
11  Blue Star 1.5 Ton 3 Star Split Inverter AC  - ...  35490
17  Panasonic 1 Ton 5 Star Split Inverter AC with ...  36490
8   Godrej 1.5 Ton 5 Star Split Inverter Convertib...  36960
19  Blue Star Convertible 4-in-1 Cooling 1 Ton 5 S...  36990
4     Lloyd 1.5 Ton 5 Star Split Inverter AC  - White  36999
0    Voltas 1.5 Ton 5 Star Split Inverter AC  - White  37499
12  Panasonic 1.5 Ton 3 Star Split Inverter AC wit...  37990
15  CARRIER Flexicool Convertible 4-in-1 Cooling 1...  37999
16  CARRIER Flexicool Convertible 4-in-1 Cooling 1...  38499
7   SAMSUNG 1.5 Ton 5 Star Split Inverter AC  - White  39999
14  CARRIER 1.5 Ton 5 Star Split Inverter AC  - White  39999
3   CARRIER Flexicool Convertible 6-in-1 Cooling 1...  40990
10  Panasonic 1.5 Ton 5 Star Split Inverter AC wit...  43990
21  CARRIER Flexicool Convertible 4-in-1 Cooling 2...  51999