In [ ]:
import pandas as pd
import requests
import urllib.request
import re

In [ ]:
# we have a string and say we want to split the string based on some delimiter
# delimiter could be anything, say we'll take comma (,) as a delimiter

text = "Good boy, boomer"
print(text.split(","))
print(text.split("b"))

['Good boy', ' boomer']
['Good ', 'oy, ', 'oomer']

In [ ]:
# Say we want to remove the comma in our string
# One dumb way is to split the string based on all commas
# Then join the list back 
text_split = text.split(",")
text_join = "".join(text_split)
print(text_join)

# We'll later talk about text pattern processing using which we could
# achieve any kind of pattern matching in our text
# and we'd be able to remove commas or any unwanted text from strings

Good boy boomer

In [ ]:
df = pd.read_csv("https://confrecordings.ams3.digitaloceanspaces.com/Reviews.csv")

In [ ]:
df

                                              Tweets  Ratings
0                      Hii , This Product is awesome        2
1                      You can definetely give a try        3
2        This one is not good as it is seems on site        1
3                  The quality of this dress is good        5
4                          I like this one very much        1
5  Delivery ..worst in small cities like .. bhopa...        0
6  Nice genuine product with high quality clear s...        4
7                      Customer Service is too worst        1
8  Got this device yesterday.The audio quality is...        3

In [ ]:
url = "https://github.com/cookieSensei/NLP/raw/main/resources/mbox-short.txt"

our_file = urllib.request.urlopen(url)

for line in our_file:
    print(line)

b'From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008\n'
b'Return-Path: <postmaster@collab.sakaiproject.org>\n'
b'Received: from murder (mail.umich.edu [141.211.14.90])\n'
b'\t by frankenstein.mail.umich.edu (Cyrus v2.3.8) with LMTPA;\n'
b'\t Sat, 05 Jan 2008 09:14:16 -0500\n'
b'X-Sieve: CMU Sieve 2.3\n'
b'Received: from murder ([unix socket])\n'
b'\t by mail.umich.edu (Cyrus v2.2.12) with LMTPA;\n'
b'\t Sat, 05 Jan 2008 09:14:16 -0500\n'
b'Received: from holes.mr.itd.umich.edu (holes.mr.itd.umich.edu [141.211.14.79])\n'
b'\tby flawless.mail.umich.edu () with ESMTP id m05EEFR1013674;\n'
b'\tSat, 5 Jan 2008 09:14:15 -0500\n'
b'Received: FROM paploo.uhi.ac.uk (app1.prod.collab.uhi.ac.uk [194.35.219.184])\n'
b'\tBY holes.mr.itd.umich.edu ID 477F90B0.2DB2F.12494 ; \n'
b'\t 5 Jan 2008 09:14:10 -0500\n'
b'Received: from paploo.uhi.ac.uk (localhost [127.0.0.1])\n'
b'\tby paploo.uhi.ac.uk (Postfix) with ESMTP id 5F919BC2F2;\n'
b'\tSat,  5 Jan 2008 14:10:05 +0000 (GMT)\n'
b'Message-ID: <200801051412.m05ECIaH010327@nakamura.uits.iupui.edu>\n'
b'Mime-Version: 1.0\n'
b'Content-Transfer-Encoding: 7bit\n'
b'Received: from prod.collab.uhi.ac.uk ([194.35.219.182])\n'
b'          by paploo.uhi.ac.uk (JAMES SMTP Server 2.1.3) with SMTP ID 899\n'
b'          for <source@collab.sakaiproject.org>;\n'
b'          Sat, 5 Jan 2008 14:09:50 +0000 (GMT)\n'
b'Received: from nakamura.uits.iupui.edu (nakamura.uits.iupui.edu [134.68.220.122])\n'
b'\tby shmi.uhi.ac.uk (Postfix) with ESMTP id A215243002\n'
b'\tfor <source@collab.sakaiproject.org>; Sat,  5 Jan 2008 14:13:33 +0000 (GMT)\n'
b'Received: from nakamura.uits.iupui.edu (localhost [127.0.0.1])\n'
b'\tby nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11) with ESMTP id m05ECJVp010329\n'
b'\tfor <source@collab.sakaiproject.org>; Sat, 5 Jan 2008 09:12:19 -0500\n'
b'Received: (from apache@localhost)\n'
b'\tby nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11/Submit) id m05ECIaH010327\n'
b'\tfor source@collab.sakaiproject.org; Sat, 5 Jan 2008 09:12:18 -0500\n'
b'Date: Sat, 5 Jan 2008 09:12:18 -0500\n'
b'X-Authentication-Warning: nakamura.uits.iupui.edu: apache set sender to stephen.marquard@uct.ac.za using -f\n'
b'To: source@collab.sakaiproject.org\n'
b'From: stephen.marquard@uct.ac.za\n'
b'Subject: [sakai] svn commit: r39772 - content/branches/sakai_2-5-x/content-impl/impl/src/java/org/sakaiproject/content/impl\n'
b'X-Content-Type-Outer-Envelope: text/plain; charset=UTF-8\n'
b'X-Content-Type-Message-Body: text/plain; charset=UTF-8\n'
b'Content-Type: text/plain; charset=UTF-8\n'
b'X-DSPAM-Result: Innocent\n'
b'X-DSPAM-Processed: Sat Jan  5 09:14:16 2008\n'
b'X-DSPAM-Confidence: 0.8475\n'
b'X-DSPAM-Probability: 0.0000\n'
b'\n'
b'Details: http://source.sakaiproject.org/viewsvn/?view=rev&rev=39772\n'
b'\n'
b'Author: stephen.marquard@uct.ac.za\n'
b'Date: 2008-01-05 09:12:07 -0500 (Sat, 05 Jan 2008)\n'
b'New Revision: 39772\n'
b'\n'
b'Modified:\n'
b'content/branches/sakai_2-5-x/content-impl/impl/src/java/org/sakaiproject/content/impl/ContentServiceSqlOracle.java\n'
b'content/branches/sakai_2-5-x/content-impl/impl/src/java/org/sakaiproject/content/impl/DbContentService.java\n'
b'Log:\n'
b'SAK-12501 merge to 2-5-x: r39622, r39624:5, r39632:3 (resolve conflict from differing linebreaks for r39622)\n'
b'\n'
b'----------------------\n'
b'This automatic notification message was sent by Sakai Collab (https://collab.sakaiproject.org/portal) from the Source site.\n'
b'You can modify how you receive notifications at My Workspace > Preferences.\n'
b'\n'
b'\n'
b'\n'
b'From louis@media.berkeley.edu Fri Jan  4 18:10:48 2008\n'
b'Return-Path: <postmaster@collab.sakaiproject.org>\n'
b'Received: from murder (mail.umich.edu [141.211.14.97])\n'
b'\t by frankenstein.mail.umich.edu (Cyrus v2.3.8) with LMTPA;\n'
b'\t Fri, 04 Jan 2008 18:10:48 -0500\n'
b'X-Sieve: CMU Sieve 2.3\n'
b'Received: from murder ([unix socket])\n'
b'\t by mail.umich.edu (Cyrus v2.2.12) with LMTPA;\n'
b'\t Fri, 04 Jan 2008 18:10:48 -0500\n'
b'Received: from icestorm.mr.itd.umich.edu (icestorm.mr.itd.umich.edu [141.211.93.149])\n'
b'\tby sleepers.mail.umich.edu () with ESMTP id m04NAbGa029441;\n'
b'\tFri, 4 Jan 2008 18:10:37 -0500\n'
b'Received: FROM paploo.uhi.ac.uk (app1.prod.collab.uhi.ac.uk [194.35.219.184])\n'
b'\tBY icestorm.mr.itd.umich.edu ID 477EBCE3.161BB.4320 ; \n'
b'\t 4 Jan 2008 18:10:31 -0500\n'
b'Received: from paploo.uhi.ac.uk (localhost [127.0.0.1])\n'
b'\tby paploo.uhi.ac.uk (Postfix) with ESMTP id 07969BB706;\n'
b'\tFri,  4 Jan 2008 23:10:33 +0000 (GMT)\n'
b'Message-ID: <200801042308.m04N8v6O008125@nakamura.uits.iupui.edu>\n'
b'Mime-Version: 1.0\n'
b'Content-Transfer-Encoding: 7bit\n'
b'Received: from prod.collab.uhi.ac.uk ([194.35.219.182])\n'
b'          by paploo.uhi.ac.uk (JAMES SMTP Server 2.1.3) with SMTP ID 710\n'
b'          for <source@collab.sakaiproject.org>;\n'
b'          Fri, 4 Jan 2008 23:10:10 +0000 (GMT)\n'
b'Received: from nakamura.uits.iupui.edu (nakamura.uits.iupui.edu [134.68.220.122])\n'
b'\tby shmi.uhi.ac.uk (Postfix) with ESMTP id 4BA2F42F57\n'
b'\tfor <source@collab.sakaiproject.org>; Fri,  4 Jan 2008 23:10:10 +0000 (GMT)\n'
b'Received: from nakamura.uits.iupui.edu (localhost [127.0.0.1])\n'
b'\tby nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11) with ESMTP id m04N8vHG008127\n'
b'\tfor <source@collab.sakaiproject.org>; Fri, 4 Jan 2008 18:08:57 -0500\n'
b'Received: (from apache@localhost)\n'
b'\tby nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11/Submit) id m04N8v6O008125\n'
b'\tfor source@collab.sakaiproject.org; Fri, 4 Jan 2008 18:08:57 -0500\n'
b'Date: Fri, 4 Jan 2008 18:08:57 -0500\n'
b'X-Authentication-Warning: nakamura.uits.iupui.edu: apache set sender to louis@media.berkeley.edu using -f\n'
b'To: source@collab.sakaiproject.org\n'
b'From: louis@media.berkeley.edu\n'
b'Subject: [sakai] svn commit: r39771 - in bspace/site-manage/sakai_2-4-x/site-manage-tool/tool/src: bundle java/org/sakaiproject/site/tool\n'
b'X-Content-Type-Outer-Envelope: text/plain; charset=UTF-8\n'
b'X-Content-Type-Message-Body: text/plain; charset=UTF-8\n'
b'Content-Type: text/plain; charset=UTF-8\n'
b'X-DSPAM-Result: Innocent\n'
b'X-DSPAM-Processed: Fri Jan  4 18:10:48 2008\n'
b'X-DSPAM-Confidence: 0.6178\n'
b'X-DSPAM-Probability: 0.0000\n'
b'\n'
b'Details: http://source.sakaiproject.org/viewsvn/?view=rev&rev=39771\n'
b'\n'
b'Author: louis@media.berkeley.edu\n'
b'Date: 2008-01-04 18:08:50 -0500 (Fri, 04 Jan 2008)\n'
b'New Revision: 39771\n'
b'\n'
b'Modified:\n'
b'bspace/site-manage/sakai_2-4-x/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties\n'
b'bspace/site-manage/sakai_2-4-x/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java\n'
b'Log:\n'
b'BSP-1415 New (Guest) user Notification\n'
b'\n'
b'----------------------\n'
b'This automatic notification message was sent by Sakai Collab (https://collab.sakaiproject.org/portal) from the Source site.\n'
b'You can modify how you receive notifications at My Workspace > Preferences.\n'
b'\n'
b'\n'
b'\n'
b'From zqian@umich.edu Fri Jan  4 16:10:39 2008\n'
b'Return-Path: <postmaster@collab.sakaiproject.org>\n'
b'Received: from murder (mail.umich.edu [141.211.14.25])\n'
b'\t by frankenstein.mail.umich.edu (Cyrus v2.3.8) with LMTPA;\n'
b'\t Fri, 04 Jan 2008 16:10:39 -0500\n'
b'X-Sieve: CMU Sieve 2.3\n'
b'Received: from murder ([unix socket])\n'
b'\t by mail.umich.edu (Cyrus v2.2.12) with LMTPA;\n'
b'\t Fri, 04 Jan 2008 16:10:39 -0500\n'
b'Received: from ghostbusters.mr.itd.umich.edu (ghostbusters.mr.itd.umich.edu [141.211.93.144])\n'
b'\tby panther.mail.umich.edu () with ESMTP id m04LAcZw014275;\n'
b'\tFri, 4 Jan 2008 16:10:38 -0500\n'
b'Received: FROM paploo.uhi.ac.uk (app1.prod.collab.uhi.ac.uk [194.35.219.184])\n'
b'\tBY ghostbusters.mr.itd.umich.edu ID 477EA0C6.A0214.25480 ; \n'
b'\t 4 Jan 2008 16:10:33 -0500\n'
b'Received: from paploo.uhi.ac.uk (localhost [127.0.0.1])\n'
b'\tby paploo.uhi.ac.uk (Postfix) with ESMTP id C48CDBB490;\n'
b'\tFri,  4 Jan 2008 21:10:31 +0000 (GMT)\n'
b'Message-ID: <200801042109.m04L92hb007923@nakamura.uits.iupui.edu>\n'
b'Mime-Version: 1.0\n'
b'Content-Transfer-Encoding: 7bit\n'
b'Received: from prod.collab.uhi.ac.uk ([194.35.219.182])\n'
b'          by paploo.uhi.ac.uk (JAMES SMTP Server 2.1.3) with SMTP ID 906\n'
b'          for <source@collab.sakaiproject.org>;\n'
b'          Fri, 4 Jan 2008 21:10:18 +0000 (GMT)\n'
b'Received: from nakamura.uits.iupui.edu (nakamura.uits.iupui.edu [134.68.220.122])\n'
b'\tby shmi.uhi.ac.uk (Postfix) with ESMTP id 7D13042F71\n'
b'\tfor <source@collab.sakaiproject.org>; Fri,  4 Jan 2008 21:10:14 +0000 (GMT)\n'
b'Received: from nakamura.uits.iupui.edu (localhost [127.0.0.1])\n'
b'\tby nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11) with ESMTP id m04L927E007925\n'
b'\tfor <source@collab.sakaiproject.org>; Fri, 4 Jan 2008 16:09:02 -0500\n'
b'Received: (from apache@localhost)\n'
b'\tby nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11/Submit) id m04L92hb007923\n'
b'\tfor source@collab.sakaiproject.org; Fri, 4 Jan 2008 16:09:02 -0500\n'
b'Date: Fri, 4 Jan 2008 16:09:02 -0500\n'
b'X-Authentication-Warning: nakamura.uits.iupui.edu: apache set sender to zqian@umich.edu using -f\n'
b'To: source@collab.sakaiproject.org\n'
b'From: zqian@umich.edu\n'
b'Subject: [sakai] svn commit: r39770 - site-manage/branches/sakai_2-5-x/site-manage-tool/tool/src/webapp/vm/sitesetup\n'
b'X-Content-Type-Outer-Envelope: text/plain; charset=UTF-8\n'
b'X-Content-Type-Message-Body: text/plain; charset=UTF-8\n'
b'Content-Type: text/plain; charset=UTF-8\n'
b'X-DSPAM-Result: Innocent\n'
b'X-DSPAM-Processed: Fri Jan  4 16:10:39 2008\n'
b'X-DSPAM-Confidence: 0.6961\n'
b'X-DSPAM-Probability: 0.0000\n'
b'\n'
b'Details: http://source.sakaiproject.org/viewsvn/?view=rev&rev=39770\n'
b'\n'
b'Author: zqian@umich.edu\n'
b'Date: 2008-01-04 16:09:01 -0500 (Fri, 04 Jan 2008)\n'
b'New Revision: 39770\n'
b'\n'
b'Modified:\n'
b'site-manage/branches/sakai_2-5-x/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm\n'
b'Log:\n'
b'merge fix to SAK-9996 into 2-5-x branch: svn merge -r 39687:39688 https://source.sakaiproject.org/svn/site-manage/trunk/\n'
b'\n'
b'----------------------\n'
b'This automatic notification message was sent by Sakai Collab (https://collab.sakaiproject.org/portal) from the Source site.\n'
b'You can modify how you receive notifications at My Workspace > Preferences.\n'
b'\n'
b'\n'
b'\n'
b'From rjlowe@iupui.edu Fri Jan  4 15:46:24 2008\n'
b'Return-Path: <postmaster@collab.sakaiproject.org>\n'
b'Received: from murder (mail.umich.edu [141.211.14.25])\n'
b'\t by frankenstein.mail.umich.edu (Cyrus v2.3.8) with LMTPA;\n'
b'\t Fri, 04 Jan 2008 15:46:24 -0500\n'
b'X-Sieve: CMU Sieve 2.3\n'
b'Received: from murder ([unix socket])\n'
b'\t by mail.umich.edu (Cyrus v2.2.12) with LMTPA;\n'
b'\t Fri, 04 Jan 2008 15:46:24 -0500\n'
b'Received: from dreamcatcher.mr.itd.umich.edu (dreamcatcher.mr.itd.umich.edu [141.211.14.43])\n'
b'\tby panther.mail.umich.edu () with ESMTP id m04KkNbx032077;\n'
b'\tFri, 4 Jan 2008 15:46:23 -0500\n'
b'Received: FROM paploo.uhi.ac.uk (app1.prod.collab.uhi.ac.uk [194.35.219.184])\n'
b'\tBY dreamcatcher.mr.itd.umich.edu ID 477E9B13.2F3BC.22965 ; \n'
b'\t 4 Jan 2008 15:46:13 -0500\n'
b'Received: from paploo.uhi.ac.uk (localhost [127.0.0.1])\n'
b'\tby paploo.uhi.ac.uk (Postfix) with ESMTP id 4AE03BB552;\n'
b'\tFri,  4 Jan 2008 20:46:13 +0000 (GMT)\n'
b'Message-ID: <200801042044.m04Kiem3007881@nakamura.uits.iupui.edu>\n'
b'Mime-Version: 1.0\n'
b'Content-Transfer-Encoding: 7bit\n'
b'Received: from prod.collab.uhi.ac.uk ([194.35.219.182])\n'
b'          by paploo.uhi.ac.uk (JAMES SMTP Server 2.1.3) with SMTP ID 38\n'
b'          for <source@collab.sakaiproject.org>;\n'
b'          Fri, 4 Jan 2008 20:45:56 +0000 (GMT)\n'
b'Received: from nakamura.uits.iupui.edu (nakamura.uits.iupui.edu [134.68.220.122])\n'
b'\tby shmi.uhi.ac.uk (Postfix) with ESMTP id A55D242F57\n'
b'\tfor <source@collab.sakaiproject.org>; Fri,  4 Jan 2008 20:45:52 +0000 (GMT)\n'
b'Received: from nakamura.uits.iupui.edu (localhost [127.0.0.1])\n'
b'\tby nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11) with ESMTP id m04KieqE007883\n'
b'\tfor <source@collab.sakaiproject.org>; Fri, 4 Jan 2008 15:44:40 -0500\n'
b'Received: (from apache@localhost)\n'
b'\tby nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11/Submit) id m04Kiem3007881\n'
b'\tfor source@collab.sakaiproject.org; Fri, 4 Jan 2008 15:44:40 -0500\n'
b'Date: Fri, 4 Jan 2008 15:44:40 -0500\n'
b'X-Authentication-Warning: nakamura.uits.iupui.edu: apache set sender to rjlowe@iupui.edu using -f\n'
b'To: source@collab.sakaiproject.org\n'
b'From: rjlowe@iupui.edu\n'
b'Subject: [sakai] svn commit: r39769 - in gradebook/trunk/app/ui/src: java/org/sakaiproject/tool/gradebook/ui/helpers/beans java/org/sakaiproject/tool/gradebook/ui/helpers/producers webapp/WEB-INF webapp/WEB-INF/bundle\n'
b'X-Content-Type-Outer-Envelope: text/plain; charset=UTF-8\n'
b'X-Content-Type-Message-Body: text/plain; charset=UTF-8\n'
b'Content-Type: text/plain; charset=UTF-8\n'
b'X-DSPAM-Result: Innocent\n'
b'X-DSPAM-Processed: Fri Jan  4 15:46:24 2008\n'
b'X-DSPAM-Confidence: 0.7565\n'
b'X-DSPAM-Probability: 0.0000\n'
b'\n'
b'Details: http://source.sakaiproject.org/viewsvn/?view=rev&rev=39769\n'
b'\n'
b'Author: rjlowe@iupui.edu\n'
b'Date: 2008-01-04 15:44:39 -0500 (Fri, 04 Jan 2008)\n'
b'New Revision: 39769\n'
b'\n'
b'Modified:\n'
b'gradebook/trunk/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/beans/AssignmentGradeRecordBean.java\n'
b'gradebook/trunk/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/producers/GradeGradebookItemProducer.java\n'
b'gradebook/trunk/app/ui/src/webapp/WEB-INF/applicationContext.xml\n'
b'gradebook/trunk/app/ui/src/webapp/WEB-INF/bundle/messages.properties\n'
b'gradebook/trunk/app/ui/src/webapp/WEB-INF/requestContext.xml\n'
b'Log:\n'
b'SAK-12180 - Fixed errors with grading helper\n'
b'\n'
b'----------------------\n'
b'This automatic notification message was sent by Sakai Collab (https://collab.sakaiproject.org/portal) from the Source site.\n'
b'You can modify how you receive notifications at My Workspace > Preferences.\n'
b'\n'
b'\n'
b'\n'
b'From zqian@umich.edu Fri Jan  4 15:03:18 2008\n'
b'Return-Path: <postmaster@collab.sakaiproject.org>\n'
b'Received: from murder (mail.umich.edu [141.211.14.46])\n'
b'\t by frankenstein.mail.umich.edu (Cyrus v2.3.8) with LMTPA;\n'
b'\t Fri, 04 Jan 2008 15:03:18 -0500\n'
b'X-Sieve: CMU Sieve 2.3\n'
b'Received: from murder ([unix socket])\n'
b'\t by mail.umich.edu (Cyrus v2.2.12) with LMTPA;\n'
b'\t Fri, 04 Jan 2008 15:03:18 -0500\n'
b'Received: from firestarter.mr.itd.umich.edu (firestarter.mr.itd.umich.edu [141.211.14.83])\n'
b'\tby fan.mail.umich.edu () with ESMTP id m04K3HGF006563;\n'
b'\tFri, 4 Jan 2008 15:03:17 -0500\n'
b'Received: FROM paploo.uhi.ac.uk (app1.prod.collab.uhi.ac.uk [194.35.219.184])\n'
b'\tBY firestarter.mr.itd.umich.edu ID 477E9100.8F7F4.1590 ; \n'
b'\t 4 Jan 2008 15:03:15 -0500\n'
b'Received: from paploo.uhi.ac.uk (localhost [127.0.0.1])\n'
b'\tby paploo.uhi.ac.uk (Postfix) with ESMTP id 57770BB477;\n'
b'\tFri,  4 Jan 2008 20:03:09 +0000 (GMT)\n'
b'Message-ID: <200801042001.m04K1cO0007738@nakamura.uits.iupui.edu>\n'
b'Mime-Version: 1.0\n'
b'Content-Transfer-Encoding: 7bit\n'
b'Received: from prod.collab.uhi.ac.uk ([194.35.219.182])\n'
b'          by paploo.uhi.ac.uk (JAMES SMTP Server 2.1.3) with SMTP ID 622\n'
b'          for <source@collab.sakaiproject.org>;\n'
b'          Fri, 4 Jan 2008 20:02:46 +0000 (GMT)\n'
b'Received: from nakamura.uits.iupui.edu (nakamura.uits.iupui.edu [134.68.220.122])\n'
b'\tby shmi.uhi.ac.uk (Postfix) with ESMTP id AB4D042F4D\n'
b'\tfor <source@collab.sakaiproject.org>; Fri,  4 Jan 2008 20:02:50 +0000 (GMT)\n'
b'Received: from nakamura.uits.iupui.edu (localhost [127.0.0.1])\n'
b'\tby nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11) with ESMTP id m04K1cXv007740\n'
b'\tfor <source@collab.sakaiproject.org>; Fri, 4 Jan 2008 15:01:38 -0500\n'
b'Received: (from apache@localhost)\n'
b'\tby nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11/Submit) id m04K1cO0007738\n'
b'\tfor source@collab.sakaiproject.org; Fri, 4 Jan 2008 15:01:38 -0500\n'
b'Date: Fri, 4 Jan 2008 15:01:38 -0500\n'
b'X-Authentication-Warning: nakamura.uits.iupui.edu: apache set sender to zqian@umich.edu using -f\n'
b'To: source@collab.sakaiproject.org\n'
b'From: zqian@umich.edu\n'
b'Subject: [sakai] svn commit: r39766 - site-manage/branches/sakai_2-4-x/site-manage-tool/tool/src/java/org/sakaiproject/site/tool\n'
b'X-Content-Type-Outer-Envelope: text/plain; charset=UTF-8\n'
b'X-Content-Type-Message-Body: text/plain; charset=UTF-8\n'
b'Content-Type: text/plain; charset=UTF-8\n'
b'X-DSPAM-Result: Innocent\n'
b'X-DSPAM-Processed: Fri Jan  4 15:03:18 2008\n'
b'X-DSPAM-Confidence: 0.7626\n'
b'X-DSPAM-Probability: 0.0000\n'
b'\n'
b'Details: http://source.sakaiproject.org/viewsvn/?view=rev&rev=39766\n'
b'\n'
b'Author: zqian@umich.edu\n'
b'Date: 2008-01-04 15:01:37 -0500 (Fri, 04 Jan 2008)\n'
b'New Revision: 39766\n'
b'\n'
b'Modified:\n'
b'site-manage/branches/sakai_2-4-x/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java\n'
b'Log:\n'
b'merge fix to SAK-10788 into site-manage 2.4.x branch:\n'
b'\n'
b"Sakai Source Repository  \t#38024  \tWed Nov 07 14:54:46 MST 2007  \tzqian@umich.edu  \t Fix to SAK-10788: If a provided id in a couse site is fake or doesn't provide any user information, Site Info appears to be like project site with empty participant list\n"
b'\n'
b'Watch for enrollments object being null and concatenate provider ids when there are more than one.\n'
b'Files Changed\n'
b'MODIFY /site-manage/trunk/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java \n'
b'\n'
b'\n'
b'\n'
b'\n'
b'----------------------\n'
b'This automatic notification message was sent by Sakai Collab (https://collab.sakaiproject.org/portal) from the Source site.\n'
b'You can modify how you receive notifications at My Workspace > Preferences.\n'
b'\n'
b'\n'
b'\n'
b'From rjlowe@iupui.edu Fri Jan  4 14:50:18 2008\n'
b'Return-Path: <postmaster@collab.sakaiproject.org>\n'
b'Received: from murder (mail.umich.edu [141.211.14.93])\n'
b'\t by frankenstein.mail.umich.edu (Cyrus v2.3.8) with LMTPA;\n'
b'\t Fri, 04 Jan 2008 14:50:18 -0500\n'
b'X-Sieve: CMU Sieve 2.3\n'
b'Received: from murder ([unix socket])\n'
b'\t by mail.umich.edu (Cyrus v2.2.12) with LMTPA;\n'
b'\t Fri, 04 Jan 2008 14:50:18 -0500\n'
b'Received: from eyewitness.mr.itd.umich.edu (eyewitness.mr.itd.umich.edu [141.211.93.142])\n'
b'\tby mission.mail.umich.edu () with ESMTP id m04JoHJi019755;\n'
b'\tFri, 4 Jan 2008 14:50:17 -0500\n'
b'Received: FROM paploo.uhi.ac.uk (app1.prod.collab.uhi.ac.uk [194.35.219.184])\n'
b'\tBY eyewitness.mr.itd.umich.edu ID 477E8DF2.67B91.5278 ; \n'
b'\t 4 Jan 2008 14:50:13 -0500\n'
b'Received: from paploo.uhi.ac.uk (localhost [127.0.0.1])\n'
b'\tby paploo.uhi.ac.uk (Postfix) with ESMTP id 2D1B9BB492;\n'
b'\tFri,  4 Jan 2008 19:47:10 +0000 (GMT)\n'
b'Message-ID: <200801041948.m04JmdwO007705@nakamura.uits.iupui.edu>\n'
b'Mime-Version: 1.0\n'
b'Content-Transfer-Encoding: 7bit\n'
b'Received: from prod.collab.uhi.ac.uk ([194.35.219.182])\n'
b'          by paploo.uhi.ac.uk (JAMES SMTP Server 2.1.3) with SMTP ID 960\n'
b'          for <source@collab.sakaiproject.org>;\n'
b'          Fri, 4 Jan 2008 19:46:50 +0000 (GMT)\n'
b'Received: from nakamura.uits.iupui.edu (nakamura.uits.iupui.edu [134.68.220.122])\n'
b'\tby shmi.uhi.ac.uk (Postfix) with ESMTP id B3E6742F4A\n'
b'\tfor <source@collab.sakaiproject.org>; Fri,  4 Jan 2008 19:49:51 +0000 (GMT)\n'
b'Received: from nakamura.uits.iupui.edu (localhost [127.0.0.1])\n'
b'\tby nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11) with ESMTP id m04JmeV9007707\n'
b'\tfor <source@collab.sakaiproject.org>; Fri, 4 Jan 2008 14:48:40 -0500\n'
b'Received: (from apache@localhost)\n'
b'\tby nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11/Submit) id m04JmdwO007705\n'

### Optional reading

Notice we have b" " string not our regular string. this b signifies a byte string. 


string = 'xtr' # Unicode characters (Latin-1, UCS-2 or UCS-4, depending on the widest character in the string)
By widest character, I mean the decimal value of unicode characters, which depending on the decimal value could assume different encodings supported by unicode 


bytes = b'xyz' # A sequence of octets (integers between 0 and 255)
Our machines understand only 0 and 1. So, the python interpreter first converts our python objects to machine language which is a byte object. 

1 byte means, 8 blocks of (8 bits) containing zeros and ones. Its, Base system, sooner or later, we'll encounter it, so don't worry as of now. Our decimal system has (0 to 9) 10 digits, then there's hexadecimals as well which have 16 digits from 0 to 9 and then from a to f, then we have base 2 system which consists only zeros and ones. A 8 block of zeros and ones, contains value from 0 to 255, that is a total of 256 characters.

I might be wrong here, but just trying to give an intuition that byte strings and our regular strings are different, so the byte strings need an encoding and decoding cycle

In [ ]:
url = "https://github.com/cookieSensei/NLP/raw/main/resources/mbox-short.txt"

our_file = urllib.request.urlopen(url)

for line in our_file:
    print(line.decode())

From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008

Return-Path: <postmaster@collab.sakaiproject.org>

Received: from murder (mail.umich.edu [141.211.14.90])

	 by frankenstein.mail.umich.edu (Cyrus v2.3.8) with LMTPA;

	 Sat, 05 Jan 2008 09:14:16 -0500

X-Sieve: CMU Sieve 2.3

Received: from murder ([unix socket])

	 by mail.umich.edu (Cyrus v2.2.12) with LMTPA;

	 Sat, 05 Jan 2008 09:14:16 -0500

Received: from holes.mr.itd.umich.edu (holes.mr.itd.umich.edu [141.211.14.79])

	by flawless.mail.umich.edu () with ESMTP id m05EEFR1013674;

	Sat, 5 Jan 2008 09:14:15 -0500

Received: FROM paploo.uhi.ac.uk (app1.prod.collab.uhi.ac.uk [194.35.219.184])

	BY holes.mr.itd.umich.edu ID 477F90B0.2DB2F.12494 ;

	 5 Jan 2008 09:14:10 -0500

Received: from paploo.uhi.ac.uk (localhost [127.0.0.1])

	by paploo.uhi.ac.uk (Postfix) with ESMTP id 5F919BC2F2;

	Sat,  5 Jan 2008 14:10:05 +0000 (GMT)

Message-ID: <200801051412.m05ECIaH010327@nakamura.uits.iupui.edu>

Mime-Version: 1.0

Content-Transfer-Encoding: 7bit

Received: from prod.collab.uhi.ac.uk ([194.35.219.182])

          by paploo.uhi.ac.uk (JAMES SMTP Server 2.1.3) with SMTP ID 899

          for <source@collab.sakaiproject.org>;

          Sat, 5 Jan 2008 14:09:50 +0000 (GMT)

Received: from nakamura.uits.iupui.edu (nakamura.uits.iupui.edu [134.68.220.122])

	by shmi.uhi.ac.uk (Postfix) with ESMTP id A215243002

	for <source@collab.sakaiproject.org>; Sat,  5 Jan 2008 14:13:33 +0000 (GMT)

Received: from nakamura.uits.iupui.edu (localhost [127.0.0.1])

	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11) with ESMTP id m05ECJVp010329

	for <source@collab.sakaiproject.org>; Sat, 5 Jan 2008 09:12:19 -0500

Received: (from apache@localhost)

	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11/Submit) id m05ECIaH010327

	for source@collab.sakaiproject.org; Sat, 5 Jan 2008 09:12:18 -0500

Date: Sat, 5 Jan 2008 09:12:18 -0500

X-Authentication-Warning: nakamura.uits.iupui.edu: apache set sender to stephen.marquard@uct.ac.za using -f

To: source@collab.sakaiproject.org

From: stephen.marquard@uct.ac.za

Subject: [sakai] svn commit: r39772 - content/branches/sakai_2-5-x/content-impl/impl/src/java/org/sakaiproject/content/impl

X-Content-Type-Outer-Envelope: text/plain; charset=UTF-8

X-Content-Type-Message-Body: text/plain; charset=UTF-8

Content-Type: text/plain; charset=UTF-8

X-DSPAM-Result: Innocent

X-DSPAM-Processed: Sat Jan  5 09:14:16 2008

X-DSPAM-Confidence: 0.8475

X-DSPAM-Probability: 0.0000



Details: http://source.sakaiproject.org/viewsvn/?view=rev&rev=39772



Author: stephen.marquard@uct.ac.za

Date: 2008-01-05 09:12:07 -0500 (Sat, 05 Jan 2008)

New Revision: 39772



Modified:

content/branches/sakai_2-5-x/content-impl/impl/src/java/org/sakaiproject/content/impl/ContentServiceSqlOracle.java

content/branches/sakai_2-5-x/content-impl/impl/src/java/org/sakaiproject/content/impl/DbContentService.java

Log:

SAK-12501 merge to 2-5-x: r39622, r39624:5, r39632:3 (resolve conflict from differing linebreaks for r39622)



----------------------

This automatic notification message was sent by Sakai Collab (https://collab.sakaiproject.org/portal) from the Source site.

You can modify how you receive notifications at My Workspace > Preferences.







From louis@media.berkeley.edu Fri Jan  4 18:10:48 2008

Return-Path: <postmaster@collab.sakaiproject.org>

Received: from murder (mail.umich.edu [141.211.14.97])

	 by frankenstein.mail.umich.edu (Cyrus v2.3.8) with LMTPA;

	 Fri, 04 Jan 2008 18:10:48 -0500

X-Sieve: CMU Sieve 2.3

Received: from murder ([unix socket])

	 by mail.umich.edu (Cyrus v2.2.12) with LMTPA;

	 Fri, 04 Jan 2008 18:10:48 -0500

Received: from icestorm.mr.itd.umich.edu (icestorm.mr.itd.umich.edu [141.211.93.149])

	by sleepers.mail.umich.edu () with ESMTP id m04NAbGa029441;

	Fri, 4 Jan 2008 18:10:37 -0500

Received: FROM paploo.uhi.ac.uk (app1.prod.collab.uhi.ac.uk [194.35.219.184])

	BY icestorm.mr.itd.umich.edu ID 477EBCE3.161BB.4320 ;

	 4 Jan 2008 18:10:31 -0500

Received: from paploo.uhi.ac.uk (localhost [127.0.0.1])

	by paploo.uhi.ac.uk (Postfix) with ESMTP id 07969BB706;

	Fri,  4 Jan 2008 23:10:33 +0000 (GMT)

Message-ID: <200801042308.m04N8v6O008125@nakamura.uits.iupui.edu>

Mime-Version: 1.0

Content-Transfer-Encoding: 7bit

Received: from prod.collab.uhi.ac.uk ([194.35.219.182])

          by paploo.uhi.ac.uk (JAMES SMTP Server 2.1.3) with SMTP ID 710

          for <source@collab.sakaiproject.org>;

          Fri, 4 Jan 2008 23:10:10 +0000 (GMT)

Received: from nakamura.uits.iupui.edu (nakamura.uits.iupui.edu [134.68.220.122])

	by shmi.uhi.ac.uk (Postfix) with ESMTP id 4BA2F42F57

	for <source@collab.sakaiproject.org>; Fri,  4 Jan 2008 23:10:10 +0000 (GMT)

Received: from nakamura.uits.iupui.edu (localhost [127.0.0.1])

	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11) with ESMTP id m04N8vHG008127

	for <source@collab.sakaiproject.org>; Fri, 4 Jan 2008 18:08:57 -0500

Received: (from apache@localhost)

	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11/Submit) id m04N8v6O008125

	for source@collab.sakaiproject.org; Fri, 4 Jan 2008 18:08:57 -0500

Date: Fri, 4 Jan 2008 18:08:57 -0500

X-Authentication-Warning: nakamura.uits.iupui.edu: apache set sender to louis@media.berkeley.edu using -f

To: source@collab.sakaiproject.org

From: louis@media.berkeley.edu

Subject: [sakai] svn commit: r39771 - in bspace/site-manage/sakai_2-4-x/site-manage-tool/tool/src: bundle java/org/sakaiproject/site/tool

X-Content-Type-Outer-Envelope: text/plain; charset=UTF-8

X-Content-Type-Message-Body: text/plain; charset=UTF-8

Content-Type: text/plain; charset=UTF-8

X-DSPAM-Result: Innocent

X-DSPAM-Processed: Fri Jan  4 18:10:48 2008

X-DSPAM-Confidence: 0.6178

X-DSPAM-Probability: 0.0000



Details: http://source.sakaiproject.org/viewsvn/?view=rev&rev=39771



Author: louis@media.berkeley.edu

Date: 2008-01-04 18:08:50 -0500 (Fri, 04 Jan 2008)

New Revision: 39771



Modified:

bspace/site-manage/sakai_2-4-x/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties

bspace/site-manage/sakai_2-4-x/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java

Log:

BSP-1415 New (Guest) user Notification



----------------------

This automatic notification message was sent by Sakai Collab (https://collab.sakaiproject.org/portal) from the Source site.

You can modify how you receive notifications at My Workspace > Preferences.







From zqian@umich.edu Fri Jan  4 16:10:39 2008

Return-Path: <postmaster@collab.sakaiproject.org>

Received: from murder (mail.umich.edu [141.211.14.25])

	 by frankenstein.mail.umich.edu (Cyrus v2.3.8) with LMTPA;

	 Fri, 04 Jan 2008 16:10:39 -0500

X-Sieve: CMU Sieve 2.3

Received: from murder ([unix socket])

	 by mail.umich.edu (Cyrus v2.2.12) with LMTPA;

	 Fri, 04 Jan 2008 16:10:39 -0500

Received: from ghostbusters.mr.itd.umich.edu (ghostbusters.mr.itd.umich.edu [141.211.93.144])

	by panther.mail.umich.edu () with ESMTP id m04LAcZw014275;

	Fri, 4 Jan 2008 16:10:38 -0500

Received: FROM paploo.uhi.ac.uk (app1.prod.collab.uhi.ac.uk [194.35.219.184])

	BY ghostbusters.mr.itd.umich.edu ID 477EA0C6.A0214.25480 ;

	 4 Jan 2008 16:10:33 -0500

Received: from paploo.uhi.ac.uk (localhost [127.0.0.1])

	by paploo.uhi.ac.uk (Postfix) with ESMTP id C48CDBB490;

	Fri,  4 Jan 2008 21:10:31 +0000 (GMT)

Message-ID: <200801042109.m04L92hb007923@nakamura.uits.iupui.edu>

Mime-Version: 1.0

Content-Transfer-Encoding: 7bit

Received: from prod.collab.uhi.ac.uk ([194.35.219.182])

          by paploo.uhi.ac.uk (JAMES SMTP Server 2.1.3) with SMTP ID 906

          for <source@collab.sakaiproject.org>;

          Fri, 4 Jan 2008 21:10:18 +0000 (GMT)

Received: from nakamura.uits.iupui.edu (nakamura.uits.iupui.edu [134.68.220.122])

	by shmi.uhi.ac.uk (Postfix) with ESMTP id 7D13042F71

	for <source@collab.sakaiproject.org>; Fri,  4 Jan 2008 21:10:14 +0000 (GMT)

Received: from nakamura.uits.iupui.edu (localhost [127.0.0.1])

	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11) with ESMTP id m04L927E007925

	for <source@collab.sakaiproject.org>; Fri, 4 Jan 2008 16:09:02 -0500

Received: (from apache@localhost)

	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11/Submit) id m04L92hb007923

	for source@collab.sakaiproject.org; Fri, 4 Jan 2008 16:09:02 -0500

Date: Fri, 4 Jan 2008 16:09:02 -0500

X-Authentication-Warning: nakamura.uits.iupui.edu: apache set sender to zqian@umich.edu using -f

To: source@collab.sakaiproject.org

From: zqian@umich.edu

Subject: [sakai] svn commit: r39770 - site-manage/branches/sakai_2-5-x/site-manage-tool/tool/src/webapp/vm/sitesetup

X-Content-Type-Outer-Envelope: text/plain; charset=UTF-8

X-Content-Type-Message-Body: text/plain; charset=UTF-8

Content-Type: text/plain; charset=UTF-8

X-DSPAM-Result: Innocent

X-DSPAM-Processed: Fri Jan  4 16:10:39 2008

X-DSPAM-Confidence: 0.6961

X-DSPAM-Probability: 0.0000



Details: http://source.sakaiproject.org/viewsvn/?view=rev&rev=39770



Author: zqian@umich.edu

Date: 2008-01-04 16:09:01 -0500 (Fri, 04 Jan 2008)

New Revision: 39770



Modified:

site-manage/branches/sakai_2-5-x/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm

Log:

merge fix to SAK-9996 into 2-5-x branch: svn merge -r 39687:39688 https://source.sakaiproject.org/svn/site-manage/trunk/



----------------------

This automatic notification message was sent by Sakai Collab (https://collab.sakaiproject.org/portal) from the Source site.

You can modify how you receive notifications at My Workspace > Preferences.







From rjlowe@iupui.edu Fri Jan  4 15:46:24 2008

Return-Path: <postmaster@collab.sakaiproject.org>

Received: from murder (mail.umich.edu [141.211.14.25])

	 by frankenstein.mail.umich.edu (Cyrus v2.3.8) with LMTPA;

	 Fri, 04 Jan 2008 15:46:24 -0500

X-Sieve: CMU Sieve 2.3

Received: from murder ([unix socket])

	 by mail.umich.edu (Cyrus v2.2.12) with LMTPA;

	 Fri, 04 Jan 2008 15:46:24 -0500

Received: from dreamcatcher.mr.itd.umich.edu (dreamcatcher.mr.itd.umich.edu [141.211.14.43])

	by panther.mail.umich.edu () with ESMTP id m04KkNbx032077;

	Fri, 4 Jan 2008 15:46:23 -0500

Received: FROM paploo.uhi.ac.uk (app1.prod.collab.uhi.ac.uk [194.35.219.184])

	BY dreamcatcher.mr.itd.umich.edu ID 477E9B13.2F3BC.22965 ;

	 4 Jan 2008 15:46:13 -0500

Received: from paploo.uhi.ac.uk (localhost [127.0.0.1])

	by paploo.uhi.ac.uk (Postfix) with ESMTP id 4AE03BB552;

	Fri,  4 Jan 2008 20:46:13 +0000 (GMT)

Message-ID: <200801042044.m04Kiem3007881@nakamura.uits.iupui.edu>

Mime-Version: 1.0

Content-Transfer-Encoding: 7bit

Received: from prod.collab.uhi.ac.uk ([194.35.219.182])

          by paploo.uhi.ac.uk (JAMES SMTP Server 2.1.3) with SMTP ID 38

          for <source@collab.sakaiproject.org>;

          Fri, 4 Jan 2008 20:45:56 +0000 (GMT)

Received: from nakamura.uits.iupui.edu (nakamura.uits.iupui.edu [134.68.220.122])

	by shmi.uhi.ac.uk (Postfix) with ESMTP id A55D242F57

	for <source@collab.sakaiproject.org>; Fri,  4 Jan 2008 20:45:52 +0000 (GMT)

Received: from nakamura.uits.iupui.edu (localhost [127.0.0.1])

	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11) with ESMTP id m04KieqE007883

	for <source@collab.sakaiproject.org>; Fri, 4 Jan 2008 15:44:40 -0500

Received: (from apache@localhost)

	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11/Submit) id m04Kiem3007881

	for source@collab.sakaiproject.org; Fri, 4 Jan 2008 15:44:40 -0500

Date: Fri, 4 Jan 2008 15:44:40 -0500

X-Authentication-Warning: nakamura.uits.iupui.edu: apache set sender to rjlowe@iupui.edu using -f

To: source@collab.sakaiproject.org

From: rjlowe@iupui.edu

Subject: [sakai] svn commit: r39769 - in gradebook/trunk/app/ui/src: java/org/sakaiproject/tool/gradebook/ui/helpers/beans java/org/sakaiproject/tool/gradebook/ui/helpers/producers webapp/WEB-INF webapp/WEB-INF/bundle

X-Content-Type-Outer-Envelope: text/plain; charset=UTF-8

X-Content-Type-Message-Body: text/plain; charset=UTF-8

Content-Type: text/plain; charset=UTF-8

X-DSPAM-Result: Innocent

X-DSPAM-Processed: Fri Jan  4 15:46:24 2008

X-DSPAM-Confidence: 0.7565

X-DSPAM-Probability: 0.0000



Details: http://source.sakaiproject.org/viewsvn/?view=rev&rev=39769



Author: rjlowe@iupui.edu

Date: 2008-01-04 15:44:39 -0500 (Fri, 04 Jan 2008)

New Revision: 39769



Modified:

gradebook/trunk/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/beans/AssignmentGradeRecordBean.java

gradebook/trunk/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/producers/GradeGradebookItemProducer.java

gradebook/trunk/app/ui/src/webapp/WEB-INF/applicationContext.xml

gradebook/trunk/app/ui/src/webapp/WEB-INF/bundle/messages.properties

gradebook/trunk/app/ui/src/webapp/WEB-INF/requestContext.xml

Log:

SAK-12180 - Fixed errors with grading helper



----------------------

This automatic notification message was sent by Sakai Collab (https://collab.sakaiproject.org/portal) from the Source site.

You can modify how you receive notifications at My Workspace > Preferences.







From zqian@umich.edu Fri Jan  4 15:03:18 2008

Return-Path: <postmaster@collab.sakaiproject.org>

Received: from murder (mail.umich.edu [141.211.14.46])

	 by frankenstein.mail.umich.edu (Cyrus v2.3.8) with LMTPA;

	 Fri, 04 Jan 2008 15:03:18 -0500

X-Sieve: CMU Sieve 2.3

Received: from murder ([unix socket])

	 by mail.umich.edu (Cyrus v2.2.12) with LMTPA;

	 Fri, 04 Jan 2008 15:03:18 -0500

Received: from firestarter.mr.itd.umich.edu (firestarter.mr.itd.umich.edu [141.211.14.83])

	by fan.mail.umich.edu () with ESMTP id m04K3HGF006563;

	Fri, 4 Jan 2008 15:03:17 -0500

Received: FROM paploo.uhi.ac.uk (app1.prod.collab.uhi.ac.uk [194.35.219.184])

	BY firestarter.mr.itd.umich.edu ID 477E9100.8F7F4.1590 ;

	 4 Jan 2008 15:03:15 -0500

Received: from paploo.uhi.ac.uk (localhost [127.0.0.1])

	by paploo.uhi.ac.uk (Postfix) with ESMTP id 57770BB477;

	Fri,  4 Jan 2008 20:03:09 +0000 (GMT)

Message-ID: <200801042001.m04K1cO0007738@nakamura.uits.iupui.edu>

Mime-Version: 1.0

Content-Transfer-Encoding: 7bit

Received: from prod.collab.uhi.ac.uk ([194.35.219.182])

          by paploo.uhi.ac.uk (JAMES SMTP Server 2.1.3) with SMTP ID 622

          for <source@collab.sakaiproject.org>;

          Fri, 4 Jan 2008 20:02:46 +0000 (GMT)

Received: from nakamura.uits.iupui.edu (nakamura.uits.iupui.edu [134.68.220.122])

	by shmi.uhi.ac.uk (Postfix) with ESMTP id AB4D042F4D

	for <source@collab.sakaiproject.org>; Fri,  4 Jan 2008 20:02:50 +0000 (GMT)

Received: from nakamura.uits.iupui.edu (localhost [127.0.0.1])

	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11) with ESMTP id m04K1cXv007740

	for <source@collab.sakaiproject.org>; Fri, 4 Jan 2008 15:01:38 -0500

Received: (from apache@localhost)

	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11/Submit) id m04K1cO0007738

	for source@collab.sakaiproject.org; Fri, 4 Jan 2008 15:01:38 -0500

Date: Fri, 4 Jan 2008 15:01:38 -0500

X-Authentication-Warning: nakamura.uits.iupui.edu: apache set sender to zqian@umich.edu using -f

To: source@collab.sakaiproject.org

From: zqian@umich.edu

Subject: [sakai] svn commit: r39766 - site-manage/branches/sakai_2-4-x/site-manage-tool/tool/src/java/org/sakaiproject/site/tool

X-Content-Type-Outer-Envelope: text/plain; charset=UTF-8

X-Content-Type-Message-Body: text/plain; charset=UTF-8

Content-Type: text/plain; charset=UTF-8

X-DSPAM-Result: Innocent

X-DSPAM-Processed: Fri Jan  4 15:03:18 2008

X-DSPAM-Confidence: 0.7626

X-DSPAM-Probability: 0.0000



Details: http://source.sakaiproject.org/viewsvn/?view=rev&rev=39766



Author: zqian@umich.edu

Date: 2008-01-04 15:01:37 -0500 (Fri, 04 Jan 2008)

New Revision: 39766



Modified:

site-manage/branches/sakai_2-4-x/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java

Log:

merge fix to SAK-10788 into site-manage 2.4.x branch:



Sakai Source Repository  	#38024  	Wed Nov 07 14:54:46 MST 2007  	zqian@umich.edu  	 Fix to SAK-10788: If a provided id in a couse site is fake or doesn't provide any user information, Site Info appears to be like project site with empty participant list



Watch for enrollments object being null and concatenate provider ids when there are more than one.

Files Changed

MODIFY /site-manage/trunk/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java









----------------------

This automatic notification message was sent by Sakai Collab (https://collab.sakaiproject.org/portal) from the Source site.

You can modify how you receive notifications at My Workspace > Preferences.







From rjlowe@iupui.edu Fri Jan  4 14:50:18 2008

Return-Path: <postmaster@collab.sakaiproject.org>

Received: from murder (mail.umich.edu [141.211.14.93])

	 by frankenstein.mail.umich.edu (Cyrus v2.3.8) with LMTPA;

	 Fri, 04 Jan 2008 14:50:18 -0500

X-Sieve: CMU Sieve 2.3

Received: from murder ([unix socket])

	 by mail.umich.edu (Cyrus v2.2.12) with LMTPA;

	 Fri, 04 Jan 2008 14:50:18 -0500

Received: from eyewitness.mr.itd.umich.edu (eyewitness.mr.itd.umich.edu [141.211.93.142])

	by mission.mail.umich.edu () with ESMTP id m04JoHJi019755;

	Fri, 4 Jan 2008 14:50:17 -0500

Received: FROM paploo.uhi.ac.uk (app1.prod.collab.uhi.ac.uk [194.35.219.184])

	BY eyewitness.mr.itd.umich.edu ID 477E8DF2.67B91.5278 ;

	 4 Jan 2008 14:50:13 -0500

Received: from paploo.uhi.ac.uk (localhost [127.0.0.1])

	by paploo.uhi.ac.uk (Postfix) with ESMTP id 2D1B9BB492;

	Fri,  4 Jan 2008 19:47:10 +0000 (GMT)

Message-ID: <200801041948.m04JmdwO007705@nakamura.uits.iupui.edu>

Mime-Version: 1.0

Content-Transfer-Encoding: 7bit

Received: from prod.collab.uhi.ac.uk ([194.35.219.182])

          by paploo.uhi.ac.uk (JAMES SMTP Server 2.1.3) with SMTP ID 960

          for <source@collab.sakaiproject.org>;

          Fri, 4 Jan 2008 19:46:50 +0000 (GMT)

Received: from nakamura.uits.iupui.edu (nakamura.uits.iupui.edu [134.68.220.122])

	by shmi.uhi.ac.uk (Postfix) with ESMTP id B3E6742F4A

	for <source@collab.sakaiproject.org>; Fri,  4 Jan 2008 19:49:51 +0000 (GMT)

Received: from nakamura.uits.iupui.edu (localhost [127.0.0.1])

	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11) with ESMTP id m04JmeV9007707

	for <source@collab.sakaiproject.org>; Fri, 4 Jan 2008 14:48:40 -0500

Received: (from apache@localhost)

	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11/Submit) id m04JmdwO007705

	for source@collab.sakaiproject.org; Fri, 4 Jan 2008 14:48:39 -0500

Date: Fri, 4 Jan 2008 14:48:39 -0500

X-Authentication-Warning: nakamura.uits.iupui.edu: apache set sender to rjlowe@iupui.edu using -f

To: source@collab.sakaiproject.org

From: rjlowe@iupui.edu

Subject: [sakai] svn commit: r39765 - in gradebook/trunk/app: business/src/java/org/sakaiproject/tool/gradebook/business business/src/java/org/sakaiproject/tool/gradebook/business/impl ui ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/beans ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/entity ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/params ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/producers ui/src/webapp/WEB-INF ui/src/webapp/WEB-INF/bundle ui/src/webapp/content/templates

X-Content-Type-Outer-Envelope: text/plain; charset=UTF-8

X-Content-Type-Message-Body: text/plain; charset=UTF-8

Content-Type: text/plain; charset=UTF-8

X-DSPAM-Result: Innocent

X-DSPAM-Processed: Fri Jan  4 14:50:18 2008

X-DSPAM-Confidence: 0.7556

X-DSPAM-Probability: 0.0000



Details: http://source.sakaiproject.org/viewsvn/?view=rev&rev=39765



Author: rjlowe@iupui.edu

Date: 2008-01-04 14:48:37 -0500 (Fri, 04 Jan 2008)

New Revision: 39765



Added:

gradebook/trunk/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/beans/AssignmentGradeRecordBean.java

gradebook/trunk/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/beans/AssignmentGradeRecordCreator.java

gradebook/trunk/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/entity/GradebookEntryGradeEntityProvider.java

In [ ]:
url = "https://github.com/cookieSensei/NLP/raw/main/resources/mbox-short.txt"

our_file = urllib.request.urlopen(url)

for line in our_file:
    print(line.decode().rstrip())

From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008
Return-Path: <postmaster@collab.sakaiproject.org>
Received: from murder (mail.umich.edu [141.211.14.90])
	 by frankenstein.mail.umich.edu (Cyrus v2.3.8) with LMTPA;
	 Sat, 05 Jan 2008 09:14:16 -0500
X-Sieve: CMU Sieve 2.3
Received: from murder ([unix socket])
	 by mail.umich.edu (Cyrus v2.2.12) with LMTPA;
	 Sat, 05 Jan 2008 09:14:16 -0500
Received: from holes.mr.itd.umich.edu (holes.mr.itd.umich.edu [141.211.14.79])
	by flawless.mail.umich.edu () with ESMTP id m05EEFR1013674;
	Sat, 5 Jan 2008 09:14:15 -0500
Received: FROM paploo.uhi.ac.uk (app1.prod.collab.uhi.ac.uk [194.35.219.184])
	BY holes.mr.itd.umich.edu ID 477F90B0.2DB2F.12494 ;
	 5 Jan 2008 09:14:10 -0500
Received: from paploo.uhi.ac.uk (localhost [127.0.0.1])
	by paploo.uhi.ac.uk (Postfix) with ESMTP id 5F919BC2F2;
	Sat,  5 Jan 2008 14:10:05 +0000 (GMT)
Message-ID: <200801051412.m05ECIaH010327@nakamura.uits.iupui.edu>
Mime-Version: 1.0
Content-Transfer-Encoding: 7bit
Received: from prod.collab.uhi.ac.uk ([194.35.219.182])
          by paploo.uhi.ac.uk (JAMES SMTP Server 2.1.3) with SMTP ID 899
          for <source@collab.sakaiproject.org>;
          Sat, 5 Jan 2008 14:09:50 +0000 (GMT)
Received: from nakamura.uits.iupui.edu (nakamura.uits.iupui.edu [134.68.220.122])
	by shmi.uhi.ac.uk (Postfix) with ESMTP id A215243002
	for <source@collab.sakaiproject.org>; Sat,  5 Jan 2008 14:13:33 +0000 (GMT)
Received: from nakamura.uits.iupui.edu (localhost [127.0.0.1])
	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11) with ESMTP id m05ECJVp010329
	for <source@collab.sakaiproject.org>; Sat, 5 Jan 2008 09:12:19 -0500
Received: (from apache@localhost)
	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11/Submit) id m05ECIaH010327
	for source@collab.sakaiproject.org; Sat, 5 Jan 2008 09:12:18 -0500
Date: Sat, 5 Jan 2008 09:12:18 -0500
X-Authentication-Warning: nakamura.uits.iupui.edu: apache set sender to stephen.marquard@uct.ac.za using -f
To: source@collab.sakaiproject.org
From: stephen.marquard@uct.ac.za
Subject: [sakai] svn commit: r39772 - content/branches/sakai_2-5-x/content-impl/impl/src/java/org/sakaiproject/content/impl
X-Content-Type-Outer-Envelope: text/plain; charset=UTF-8
X-Content-Type-Message-Body: text/plain; charset=UTF-8
Content-Type: text/plain; charset=UTF-8
X-DSPAM-Result: Innocent
X-DSPAM-Processed: Sat Jan  5 09:14:16 2008
X-DSPAM-Confidence: 0.8475
X-DSPAM-Probability: 0.0000

Details: http://source.sakaiproject.org/viewsvn/?view=rev&rev=39772

Author: stephen.marquard@uct.ac.za
Date: 2008-01-05 09:12:07 -0500 (Sat, 05 Jan 2008)
New Revision: 39772

Modified:
content/branches/sakai_2-5-x/content-impl/impl/src/java/org/sakaiproject/content/impl/ContentServiceSqlOracle.java
content/branches/sakai_2-5-x/content-impl/impl/src/java/org/sakaiproject/content/impl/DbContentService.java
Log:
SAK-12501 merge to 2-5-x: r39622, r39624:5, r39632:3 (resolve conflict from differing linebreaks for r39622)

----------------------
This automatic notification message was sent by Sakai Collab (https://collab.sakaiproject.org/portal) from the Source site.
You can modify how you receive notifications at My Workspace > Preferences.



From louis@media.berkeley.edu Fri Jan  4 18:10:48 2008
Return-Path: <postmaster@collab.sakaiproject.org>
Received: from murder (mail.umich.edu [141.211.14.97])
	 by frankenstein.mail.umich.edu (Cyrus v2.3.8) with LMTPA;
	 Fri, 04 Jan 2008 18:10:48 -0500
X-Sieve: CMU Sieve 2.3
Received: from murder ([unix socket])
	 by mail.umich.edu (Cyrus v2.2.12) with LMTPA;
	 Fri, 04 Jan 2008 18:10:48 -0500
Received: from icestorm.mr.itd.umich.edu (icestorm.mr.itd.umich.edu [141.211.93.149])
	by sleepers.mail.umich.edu () with ESMTP id m04NAbGa029441;
	Fri, 4 Jan 2008 18:10:37 -0500
Received: FROM paploo.uhi.ac.uk (app1.prod.collab.uhi.ac.uk [194.35.219.184])
	BY icestorm.mr.itd.umich.edu ID 477EBCE3.161BB.4320 ;
	 4 Jan 2008 18:10:31 -0500
Received: from paploo.uhi.ac.uk (localhost [127.0.0.1])
	by paploo.uhi.ac.uk (Postfix) with ESMTP id 07969BB706;
	Fri,  4 Jan 2008 23:10:33 +0000 (GMT)
Message-ID: <200801042308.m04N8v6O008125@nakamura.uits.iupui.edu>
Mime-Version: 1.0
Content-Transfer-Encoding: 7bit
Received: from prod.collab.uhi.ac.uk ([194.35.219.182])
          by paploo.uhi.ac.uk (JAMES SMTP Server 2.1.3) with SMTP ID 710
          for <source@collab.sakaiproject.org>;
          Fri, 4 Jan 2008 23:10:10 +0000 (GMT)
Received: from nakamura.uits.iupui.edu (nakamura.uits.iupui.edu [134.68.220.122])
	by shmi.uhi.ac.uk (Postfix) with ESMTP id 4BA2F42F57
	for <source@collab.sakaiproject.org>; Fri,  4 Jan 2008 23:10:10 +0000 (GMT)
Received: from nakamura.uits.iupui.edu (localhost [127.0.0.1])
	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11) with ESMTP id m04N8vHG008127
	for <source@collab.sakaiproject.org>; Fri, 4 Jan 2008 18:08:57 -0500
Received: (from apache@localhost)
	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11/Submit) id m04N8v6O008125
	for source@collab.sakaiproject.org; Fri, 4 Jan 2008 18:08:57 -0500
Date: Fri, 4 Jan 2008 18:08:57 -0500
X-Authentication-Warning: nakamura.uits.iupui.edu: apache set sender to louis@media.berkeley.edu using -f
To: source@collab.sakaiproject.org
From: louis@media.berkeley.edu
Subject: [sakai] svn commit: r39771 - in bspace/site-manage/sakai_2-4-x/site-manage-tool/tool/src: bundle java/org/sakaiproject/site/tool
X-Content-Type-Outer-Envelope: text/plain; charset=UTF-8
X-Content-Type-Message-Body: text/plain; charset=UTF-8
Content-Type: text/plain; charset=UTF-8
X-DSPAM-Result: Innocent
X-DSPAM-Processed: Fri Jan  4 18:10:48 2008
X-DSPAM-Confidence: 0.6178
X-DSPAM-Probability: 0.0000

Details: http://source.sakaiproject.org/viewsvn/?view=rev&rev=39771

Author: louis@media.berkeley.edu
Date: 2008-01-04 18:08:50 -0500 (Fri, 04 Jan 2008)
New Revision: 39771

Modified:
bspace/site-manage/sakai_2-4-x/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
bspace/site-manage/sakai_2-4-x/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Log:
BSP-1415 New (Guest) user Notification

----------------------
This automatic notification message was sent by Sakai Collab (https://collab.sakaiproject.org/portal) from the Source site.
You can modify how you receive notifications at My Workspace > Preferences.



From zqian@umich.edu Fri Jan  4 16:10:39 2008
Return-Path: <postmaster@collab.sakaiproject.org>
Received: from murder (mail.umich.edu [141.211.14.25])
	 by frankenstein.mail.umich.edu (Cyrus v2.3.8) with LMTPA;
	 Fri, 04 Jan 2008 16:10:39 -0500
X-Sieve: CMU Sieve 2.3
Received: from murder ([unix socket])
	 by mail.umich.edu (Cyrus v2.2.12) with LMTPA;
	 Fri, 04 Jan 2008 16:10:39 -0500
Received: from ghostbusters.mr.itd.umich.edu (ghostbusters.mr.itd.umich.edu [141.211.93.144])
	by panther.mail.umich.edu () with ESMTP id m04LAcZw014275;
	Fri, 4 Jan 2008 16:10:38 -0500
Received: FROM paploo.uhi.ac.uk (app1.prod.collab.uhi.ac.uk [194.35.219.184])
	BY ghostbusters.mr.itd.umich.edu ID 477EA0C6.A0214.25480 ;
	 4 Jan 2008 16:10:33 -0500
Received: from paploo.uhi.ac.uk (localhost [127.0.0.1])
	by paploo.uhi.ac.uk (Postfix) with ESMTP id C48CDBB490;
	Fri,  4 Jan 2008 21:10:31 +0000 (GMT)
Message-ID: <200801042109.m04L92hb007923@nakamura.uits.iupui.edu>
Mime-Version: 1.0
Content-Transfer-Encoding: 7bit
Received: from prod.collab.uhi.ac.uk ([194.35.219.182])
          by paploo.uhi.ac.uk (JAMES SMTP Server 2.1.3) with SMTP ID 906
          for <source@collab.sakaiproject.org>;
          Fri, 4 Jan 2008 21:10:18 +0000 (GMT)
Received: from nakamura.uits.iupui.edu (nakamura.uits.iupui.edu [134.68.220.122])
	by shmi.uhi.ac.uk (Postfix) with ESMTP id 7D13042F71
	for <source@collab.sakaiproject.org>; Fri,  4 Jan 2008 21:10:14 +0000 (GMT)
Received: from nakamura.uits.iupui.edu (localhost [127.0.0.1])
	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11) with ESMTP id m04L927E007925
	for <source@collab.sakaiproject.org>; Fri, 4 Jan 2008 16:09:02 -0500
Received: (from apache@localhost)
	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11/Submit) id m04L92hb007923
	for source@collab.sakaiproject.org; Fri, 4 Jan 2008 16:09:02 -0500
Date: Fri, 4 Jan 2008 16:09:02 -0500
X-Authentication-Warning: nakamura.uits.iupui.edu: apache set sender to zqian@umich.edu using -f
To: source@collab.sakaiproject.org
From: zqian@umich.edu
Subject: [sakai] svn commit: r39770 - site-manage/branches/sakai_2-5-x/site-manage-tool/tool/src/webapp/vm/sitesetup
X-Content-Type-Outer-Envelope: text/plain; charset=UTF-8
X-Content-Type-Message-Body: text/plain; charset=UTF-8
Content-Type: text/plain; charset=UTF-8
X-DSPAM-Result: Innocent
X-DSPAM-Processed: Fri Jan  4 16:10:39 2008
X-DSPAM-Confidence: 0.6961
X-DSPAM-Probability: 0.0000

Details: http://source.sakaiproject.org/viewsvn/?view=rev&rev=39770

Author: zqian@umich.edu
Date: 2008-01-04 16:09:01 -0500 (Fri, 04 Jan 2008)
New Revision: 39770

Modified:
site-manage/branches/sakai_2-5-x/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
Log:
merge fix to SAK-9996 into 2-5-x branch: svn merge -r 39687:39688 https://source.sakaiproject.org/svn/site-manage/trunk/

----------------------
This automatic notification message was sent by Sakai Collab (https://collab.sakaiproject.org/portal) from the Source site.
You can modify how you receive notifications at My Workspace > Preferences.



From rjlowe@iupui.edu Fri Jan  4 15:46:24 2008
Return-Path: <postmaster@collab.sakaiproject.org>
Received: from murder (mail.umich.edu [141.211.14.25])
	 by frankenstein.mail.umich.edu (Cyrus v2.3.8) with LMTPA;
	 Fri, 04 Jan 2008 15:46:24 -0500
X-Sieve: CMU Sieve 2.3
Received: from murder ([unix socket])
	 by mail.umich.edu (Cyrus v2.2.12) with LMTPA;
	 Fri, 04 Jan 2008 15:46:24 -0500
Received: from dreamcatcher.mr.itd.umich.edu (dreamcatcher.mr.itd.umich.edu [141.211.14.43])
	by panther.mail.umich.edu () with ESMTP id m04KkNbx032077;
	Fri, 4 Jan 2008 15:46:23 -0500
Received: FROM paploo.uhi.ac.uk (app1.prod.collab.uhi.ac.uk [194.35.219.184])
	BY dreamcatcher.mr.itd.umich.edu ID 477E9B13.2F3BC.22965 ;
	 4 Jan 2008 15:46:13 -0500
Received: from paploo.uhi.ac.uk (localhost [127.0.0.1])
	by paploo.uhi.ac.uk (Postfix) with ESMTP id 4AE03BB552;
	Fri,  4 Jan 2008 20:46:13 +0000 (GMT)
Message-ID: <200801042044.m04Kiem3007881@nakamura.uits.iupui.edu>
Mime-Version: 1.0
Content-Transfer-Encoding: 7bit
Received: from prod.collab.uhi.ac.uk ([194.35.219.182])
          by paploo.uhi.ac.uk (JAMES SMTP Server 2.1.3) with SMTP ID 38
          for <source@collab.sakaiproject.org>;
          Fri, 4 Jan 2008 20:45:56 +0000 (GMT)
Received: from nakamura.uits.iupui.edu (nakamura.uits.iupui.edu [134.68.220.122])
	by shmi.uhi.ac.uk (Postfix) with ESMTP id A55D242F57
	for <source@collab.sakaiproject.org>; Fri,  4 Jan 2008 20:45:52 +0000 (GMT)
Received: from nakamura.uits.iupui.edu (localhost [127.0.0.1])
	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11) with ESMTP id m04KieqE007883
	for <source@collab.sakaiproject.org>; Fri, 4 Jan 2008 15:44:40 -0500
Received: (from apache@localhost)
	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11/Submit) id m04Kiem3007881
	for source@collab.sakaiproject.org; Fri, 4 Jan 2008 15:44:40 -0500
Date: Fri, 4 Jan 2008 15:44:40 -0500
X-Authentication-Warning: nakamura.uits.iupui.edu: apache set sender to rjlowe@iupui.edu using -f
To: source@collab.sakaiproject.org
From: rjlowe@iupui.edu
Subject: [sakai] svn commit: r39769 - in gradebook/trunk/app/ui/src: java/org/sakaiproject/tool/gradebook/ui/helpers/beans java/org/sakaiproject/tool/gradebook/ui/helpers/producers webapp/WEB-INF webapp/WEB-INF/bundle
X-Content-Type-Outer-Envelope: text/plain; charset=UTF-8
X-Content-Type-Message-Body: text/plain; charset=UTF-8
Content-Type: text/plain; charset=UTF-8
X-DSPAM-Result: Innocent
X-DSPAM-Processed: Fri Jan  4 15:46:24 2008
X-DSPAM-Confidence: 0.7565
X-DSPAM-Probability: 0.0000

Details: http://source.sakaiproject.org/viewsvn/?view=rev&rev=39769

Author: rjlowe@iupui.edu
Date: 2008-01-04 15:44:39 -0500 (Fri, 04 Jan 2008)
New Revision: 39769

Modified:
gradebook/trunk/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/beans/AssignmentGradeRecordBean.java
gradebook/trunk/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/producers/GradeGradebookItemProducer.java
gradebook/trunk/app/ui/src/webapp/WEB-INF/applicationContext.xml
gradebook/trunk/app/ui/src/webapp/WEB-INF/bundle/messages.properties
gradebook/trunk/app/ui/src/webapp/WEB-INF/requestContext.xml
Log:
SAK-12180 - Fixed errors with grading helper

----------------------
This automatic notification message was sent by Sakai Collab (https://collab.sakaiproject.org/portal) from the Source site.
You can modify how you receive notifications at My Workspace > Preferences.



From zqian@umich.edu Fri Jan  4 15:03:18 2008
Return-Path: <postmaster@collab.sakaiproject.org>
Received: from murder (mail.umich.edu [141.211.14.46])
	 by frankenstein.mail.umich.edu (Cyrus v2.3.8) with LMTPA;
	 Fri, 04 Jan 2008 15:03:18 -0500
X-Sieve: CMU Sieve 2.3
Received: from murder ([unix socket])
	 by mail.umich.edu (Cyrus v2.2.12) with LMTPA;
	 Fri, 04 Jan 2008 15:03:18 -0500
Received: from firestarter.mr.itd.umich.edu (firestarter.mr.itd.umich.edu [141.211.14.83])
	by fan.mail.umich.edu () with ESMTP id m04K3HGF006563;
	Fri, 4 Jan 2008 15:03:17 -0500
Received: FROM paploo.uhi.ac.uk (app1.prod.collab.uhi.ac.uk [194.35.219.184])
	BY firestarter.mr.itd.umich.edu ID 477E9100.8F7F4.1590 ;
	 4 Jan 2008 15:03:15 -0500
Received: from paploo.uhi.ac.uk (localhost [127.0.0.1])
	by paploo.uhi.ac.uk (Postfix) with ESMTP id 57770BB477;
	Fri,  4 Jan 2008 20:03:09 +0000 (GMT)
Message-ID: <200801042001.m04K1cO0007738@nakamura.uits.iupui.edu>
Mime-Version: 1.0
Content-Transfer-Encoding: 7bit
Received: from prod.collab.uhi.ac.uk ([194.35.219.182])
          by paploo.uhi.ac.uk (JAMES SMTP Server 2.1.3) with SMTP ID 622
          for <source@collab.sakaiproject.org>;
          Fri, 4 Jan 2008 20:02:46 +0000 (GMT)
Received: from nakamura.uits.iupui.edu (nakamura.uits.iupui.edu [134.68.220.122])
	by shmi.uhi.ac.uk (Postfix) with ESMTP id AB4D042F4D
	for <source@collab.sakaiproject.org>; Fri,  4 Jan 2008 20:02:50 +0000 (GMT)
Received: from nakamura.uits.iupui.edu (localhost [127.0.0.1])
	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11) with ESMTP id m04K1cXv007740
	for <source@collab.sakaiproject.org>; Fri, 4 Jan 2008 15:01:38 -0500
Received: (from apache@localhost)
	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11/Submit) id m04K1cO0007738
	for source@collab.sakaiproject.org; Fri, 4 Jan 2008 15:01:38 -0500
Date: Fri, 4 Jan 2008 15:01:38 -0500
X-Authentication-Warning: nakamura.uits.iupui.edu: apache set sender to zqian@umich.edu using -f
To: source@collab.sakaiproject.org
From: zqian@umich.edu
Subject: [sakai] svn commit: r39766 - site-manage/branches/sakai_2-4-x/site-manage-tool/tool/src/java/org/sakaiproject/site/tool
X-Content-Type-Outer-Envelope: text/plain; charset=UTF-8
X-Content-Type-Message-Body: text/plain; charset=UTF-8
Content-Type: text/plain; charset=UTF-8
X-DSPAM-Result: Innocent
X-DSPAM-Processed: Fri Jan  4 15:03:18 2008
X-DSPAM-Confidence: 0.7626
X-DSPAM-Probability: 0.0000

Details: http://source.sakaiproject.org/viewsvn/?view=rev&rev=39766

Author: zqian@umich.edu
Date: 2008-01-04 15:01:37 -0500 (Fri, 04 Jan 2008)
New Revision: 39766

Modified:
site-manage/branches/sakai_2-4-x/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Log:
merge fix to SAK-10788 into site-manage 2.4.x branch:

Sakai Source Repository  	#38024  	Wed Nov 07 14:54:46 MST 2007  	zqian@umich.edu  	 Fix to SAK-10788: If a provided id in a couse site is fake or doesn't provide any user information, Site Info appears to be like project site with empty participant list

Watch for enrollments object being null and concatenate provider ids when there are more than one.
Files Changed
MODIFY /site-manage/trunk/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java




----------------------
This automatic notification message was sent by Sakai Collab (https://collab.sakaiproject.org/portal) from the Source site.
You can modify how you receive notifications at My Workspace > Preferences.



From rjlowe@iupui.edu Fri Jan  4 14:50:18 2008
Return-Path: <postmaster@collab.sakaiproject.org>
Received: from murder (mail.umich.edu [141.211.14.93])
	 by frankenstein.mail.umich.edu (Cyrus v2.3.8) with LMTPA;
	 Fri, 04 Jan 2008 14:50:18 -0500
X-Sieve: CMU Sieve 2.3
Received: from murder ([unix socket])
	 by mail.umich.edu (Cyrus v2.2.12) with LMTPA;
	 Fri, 04 Jan 2008 14:50:18 -0500
Received: from eyewitness.mr.itd.umich.edu (eyewitness.mr.itd.umich.edu [141.211.93.142])
	by mission.mail.umich.edu () with ESMTP id m04JoHJi019755;
	Fri, 4 Jan 2008 14:50:17 -0500
Received: FROM paploo.uhi.ac.uk (app1.prod.collab.uhi.ac.uk [194.35.219.184])
	BY eyewitness.mr.itd.umich.edu ID 477E8DF2.67B91.5278 ;
	 4 Jan 2008 14:50:13 -0500
Received: from paploo.uhi.ac.uk (localhost [127.0.0.1])
	by paploo.uhi.ac.uk (Postfix) with ESMTP id 2D1B9BB492;
	Fri,  4 Jan 2008 19:47:10 +0000 (GMT)
Message-ID: <200801041948.m04JmdwO007705@nakamura.uits.iupui.edu>
Mime-Version: 1.0
Content-Transfer-Encoding: 7bit
Received: from prod.collab.uhi.ac.uk ([194.35.219.182])
          by paploo.uhi.ac.uk (JAMES SMTP Server 2.1.3) with SMTP ID 960
          for <source@collab.sakaiproject.org>;
          Fri, 4 Jan 2008 19:46:50 +0000 (GMT)
Received: from nakamura.uits.iupui.edu (nakamura.uits.iupui.edu [134.68.220.122])
	by shmi.uhi.ac.uk (Postfix) with ESMTP id B3E6742F4A
	for <source@collab.sakaiproject.org>; Fri,  4 Jan 2008 19:49:51 +0000 (GMT)
Received: from nakamura.uits.iupui.edu (localhost [127.0.0.1])
	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11) with ESMTP id m04JmeV9007707
	for <source@collab.sakaiproject.org>; Fri, 4 Jan 2008 14:48:40 -0500
Received: (from apache@localhost)
	by nakamura.uits.iupui.edu (8.12.11.20060308/8.12.11/Submit) id m04JmdwO007705
	for source@collab.sakaiproject.org; Fri, 4 Jan 2008 14:48:39 -0500
Date: Fri, 4 Jan 2008 14:48:39 -0500
X-Authentication-Warning: nakamura.uits.iupui.edu: apache set sender to rjlowe@iupui.edu using -f
To: source@collab.sakaiproject.org
From: rjlowe@iupui.edu
Subject: [sakai] svn commit: r39765 - in gradebook/trunk/app: business/src/java/org/sakaiproject/tool/gradebook/business business/src/java/org/sakaiproject/tool/gradebook/business/impl ui ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/beans ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/entity ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/params ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/producers ui/src/webapp/WEB-INF ui/src/webapp/WEB-INF/bundle ui/src/webapp/content/templates
X-Content-Type-Outer-Envelope: text/plain; charset=UTF-8
X-Content-Type-Message-Body: text/plain; charset=UTF-8
Content-Type: text/plain; charset=UTF-8
X-DSPAM-Result: Innocent
X-DSPAM-Processed: Fri Jan  4 14:50:18 2008
X-DSPAM-Confidence: 0.7556
X-DSPAM-Probability: 0.0000

Details: http://source.sakaiproject.org/viewsvn/?view=rev&rev=39765

Author: rjlowe@iupui.edu
Date: 2008-01-04 14:48:37 -0500 (Fri, 04 Jan 2008)
New Revision: 39765

Added:
gradebook/trunk/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/beans/AssignmentGradeRecordBean.java
gradebook/trunk/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/beans/AssignmentGradeRecordCreator.java
gradebook/trunk/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/entity/GradebookEntryGradeEntityProvider.java
gradebook/trunk/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/params/GradeGradebookItemViewParams.java
gradebook/trunk/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/producers/GradeGradebookItemProducer.java
gradebook/trunk/app/ui/src/webapp/content/templates/grade-gradebook-item.html
Modified:

In [ ]:
url = "https://github.com/cookieSensei/NLP/raw/main/resources/mbox-short.txt"

our_file = urllib.request.urlopen(url)

for line in our_file:
    # print(line.decode().rstrip())
    # .split() breaks the string by a whitespace character (default delimiter)
    words = line.decode().rstrip().split()
    for word in words:
        print(word)

Streaming output truncated to the last 5000 lines.
-
in
site-manage/trunk/site-manage-tool/tool/src:
java/org/sakaiproject/site/tool
webapp/vm/sitesetup
X-Content-Type-Outer-Envelope:
text/plain;
charset=UTF-8
X-Content-Type-Message-Body:
text/plain;
charset=UTF-8
Content-Type:
text/plain;
charset=UTF-8
X-DSPAM-Result:
Innocent
X-DSPAM-Processed:
Fri
Jan
4
11:11:03
2008
X-DSPAM-Confidence:
0.6959
X-DSPAM-Probability:
0.0000
Details:
http://source.sakaiproject.org/viewsvn/?view=rev&rev=39760
Author:
zqian@umich.edu
Date:
2008-01-04
11:09:12
-0500
(Fri,
04
Jan
2008)
New
Revision:
39760
Modified:
site-manage/trunk/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
site-manage/trunk/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
Log:
fix
to
SAK-10911:
Refactor
use
of
site.upd,
site.upd.site.mbrship
and
site.upd.grp.mbrship
permissions
----------------------
This
automatic
notification
message
was
sent
by
Sakai
Collab
(https://collab.sakaiproject.org/portal)
from
the
Source
site.
You
can
modify
how
you
receive
notifications
at
My
Workspace
>
Preferences.
From
gsilver@umich.edu
Fri
Jan
4
11:10:22
2008
Return-Path:
<postmaster@collab.sakaiproject.org>
Received:
from
murder
(mail.umich.edu
[141.211.14.39])
by
frankenstein.mail.umich.edu
(Cyrus
v2.3.8)
with
LMTPA;
Fri,
04
Jan
2008
11:10:22
-0500
X-Sieve:
CMU
Sieve
2.3
Received:
from
murder
([unix
socket])
by
mail.umich.edu
(Cyrus
v2.2.12)
with
LMTPA;
Fri,
04
Jan
2008
11:10:22
-0500
Received:
from
holes.mr.itd.umich.edu
(holes.mr.itd.umich.edu
[141.211.14.79])
by
faithful.mail.umich.edu
()
with
ESMTP
id
m04GAL9k010604;
Fri,
4
Jan
2008
11:10:21
-0500
Received:
FROM
paploo.uhi.ac.uk
(app1.prod.collab.uhi.ac.uk
[194.35.219.184])
BY
holes.mr.itd.umich.edu
ID
477E5A67.34350.23015
;
4
Jan
2008
11:10:18
-0500
Received:
from
paploo.uhi.ac.uk
(localhost
[127.0.0.1])
by
paploo.uhi.ac.uk
(Postfix)
with
ESMTP
id
98D04BAD43;
Fri,
4
Jan
2008
16:10:11
+0000
(GMT)
Message-ID:
<200801041608.m04G8d7w007184@nakamura.uits.iupui.edu>
Mime-Version:
1.0
Content-Transfer-Encoding:
7bit
Received:
from
prod.collab.uhi.ac.uk
([194.35.219.182])
by
paploo.uhi.ac.uk
(JAMES
SMTP
Server
2.1.3)
with
SMTP
ID
966
for
<source@collab.sakaiproject.org>;
Fri,
4
Jan
2008
16:09:51
+0000
(GMT)
Received:
from
nakamura.uits.iupui.edu
(nakamura.uits.iupui.edu
[134.68.220.122])
by
shmi.uhi.ac.uk
(Postfix)
with
ESMTP
id
9F89542DD0
for
<source@collab.sakaiproject.org>;
Fri,
4
Jan
2008
16:09:50
+0000
(GMT)
Received:
from
nakamura.uits.iupui.edu
(localhost
[127.0.0.1])
by
nakamura.uits.iupui.edu
(8.12.11.20060308/8.12.11)
with
ESMTP
id
m04G8dXN007186
for
<source@collab.sakaiproject.org>;
Fri,
4
Jan
2008
11:08:39
-0500
Received:
(from
apache@localhost)
by
nakamura.uits.iupui.edu
(8.12.11.20060308/8.12.11/Submit)
id
m04G8d7w007184
for
source@collab.sakaiproject.org;
Fri,
4
Jan
2008
11:08:39
-0500
Date:
Fri,
4
Jan
2008
11:08:39
-0500
X-Authentication-Warning:
nakamura.uits.iupui.edu:
apache
set
sender
to
gsilver@umich.edu
using
-f
To:
source@collab.sakaiproject.org
From:
gsilver@umich.edu
Subject:
[sakai]
svn
commit:
r39759
-
mailarchive/trunk/mailarchive-tool/tool/src/bundle
X-Content-Type-Outer-Envelope:
text/plain;
charset=UTF-8
X-Content-Type-Message-Body:
text/plain;
charset=UTF-8
Content-Type:
text/plain;
charset=UTF-8
X-DSPAM-Result:
Innocent
X-DSPAM-Processed:
Fri
Jan
4
11:10:22
2008
X-DSPAM-Confidence:
0.7606
X-DSPAM-Probability:
0.0000
Details:
http://source.sakaiproject.org/viewsvn/?view=rev&rev=39759
Author:
gsilver@umich.edu
Date:
2008-01-04
11:08:38
-0500
(Fri,
04
Jan
2008)
New
Revision:
39759
Modified:
mailarchive/trunk/mailarchive-tool/tool/src/bundle/email.properties
Log:
SAK-12592
http://bugs.sakaiproject.org/jira/browse/SAK-12592
-
left
moot
(unused)
entries
commented
for
now
----------------------
This
automatic
notification
message
was
sent
by
Sakai
Collab
(https://collab.sakaiproject.org/portal)
from
the
Source
site.
You
can
modify
how
you
receive
notifications
at
My
Workspace
>
Preferences.
From
wagnermr@iupui.edu
Fri
Jan
4
10:38:42
2008
Return-Path:
<postmaster@collab.sakaiproject.org>
Received:
from
murder
(mail.umich.edu
[141.211.14.90])
by
frankenstein.mail.umich.edu
(Cyrus
v2.3.8)
with
LMTPA;
Fri,
04
Jan
2008
10:38:42
-0500
X-Sieve:
CMU
Sieve
2.3
Received:
from
murder
([unix
socket])
by
mail.umich.edu
(Cyrus
v2.2.12)
with
LMTPA;
Fri,
04
Jan
2008
10:38:42
-0500
Received:
from
shining.mr.itd.umich.edu
(shining.mr.itd.umich.edu
[141.211.93.153])
by
flawless.mail.umich.edu
()
with
ESMTP
id
m04Fcfjm012313;
Fri,
4
Jan
2008
10:38:41
-0500
Received:
FROM
paploo.uhi.ac.uk
(app1.prod.collab.uhi.ac.uk
[194.35.219.184])
BY
shining.mr.itd.umich.edu
ID
477E52FA.E6C6E.24093
;
4
Jan
2008
10:38:37
-0500
Received:
from
paploo.uhi.ac.uk
(localhost
[127.0.0.1])
by
paploo.uhi.ac.uk
(Postfix)
with
ESMTP
id
6A39594CD2;
Fri,
4
Jan
2008
15:37:36
+0000
(GMT)
Message-ID:
<200801041537.m04Fb6Ci007092@nakamura.uits.iupui.edu>
Mime-Version:
1.0
Content-Transfer-Encoding:
7bit
Received:
from
prod.collab.uhi.ac.uk
([194.35.219.182])
by
paploo.uhi.ac.uk
(JAMES
SMTP
Server
2.1.3)
with
SMTP
ID
690
for
<source@collab.sakaiproject.org>;
Fri,
4
Jan
2008
15:37:21
+0000
(GMT)
Received:
from
nakamura.uits.iupui.edu
(nakamura.uits.iupui.edu
[134.68.220.122])
by
shmi.uhi.ac.uk
(Postfix)
with
ESMTP
id
CEFA037ACE
for
<source@collab.sakaiproject.org>;
Fri,
4
Jan
2008
15:38:17
+0000
(GMT)
Received:
from
nakamura.uits.iupui.edu
(localhost
[127.0.0.1])
by
nakamura.uits.iupui.edu
(8.12.11.20060308/8.12.11)
with
ESMTP
id
m04Fb6nh007094
for
<source@collab.sakaiproject.org>;
Fri,
4
Jan
2008
10:37:06
-0500
Received:
(from
apache@localhost)
by
nakamura.uits.iupui.edu
(8.12.11.20060308/8.12.11/Submit)
id
m04Fb6Ci007092
for
source@collab.sakaiproject.org;
Fri,
4
Jan
2008
10:37:06
-0500
Date:
Fri,
4
Jan
2008
10:37:06
-0500
X-Authentication-Warning:
nakamura.uits.iupui.edu:
apache
set
sender
to
wagnermr@iupui.edu
using
-f
To:
source@collab.sakaiproject.org
From:
wagnermr@iupui.edu
Subject:
[sakai]
svn
commit:
r39758
-
in
gradebook/trunk:
app/business/src/java/org/sakaiproject/tool/gradebook/business/impl
service/api/src/java/org/sakaiproject/service/gradebook/shared
service/impl/src/java/org/sakaiproject/component/gradebook
X-Content-Type-Outer-Envelope:
text/plain;
charset=UTF-8
X-Content-Type-Message-Body:
text/plain;
charset=UTF-8
Content-Type:
text/plain;
charset=UTF-8
X-DSPAM-Result:
Innocent
X-DSPAM-Processed:
Fri
Jan
4
10:38:42
2008
X-DSPAM-Confidence:
0.7559
X-DSPAM-Probability:
0.0000
Details:
http://source.sakaiproject.org/viewsvn/?view=rev&rev=39758
Author:
wagnermr@iupui.edu
Date:
2008-01-04
10:37:04
-0500
(Fri,
04
Jan
2008)
New
Revision:
39758
Modified:
gradebook/trunk/app/business/src/java/org/sakaiproject/tool/gradebook/business/impl/GradebookManagerHibernateImpl.java
gradebook/trunk/service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookService.java
gradebook/trunk/service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
Log:
SAK-12175
http://bugs.sakaiproject.org/jira/browse/SAK-12175
Create
methods
required
for
gb
integration
with
the
Assignment2
tool
getGradeDefinitionForStudentForItem
----------------------
This
automatic
notification
message
was
sent
by
Sakai
Collab
(https://collab.sakaiproject.org/portal)
from
the
Source
site.
You
can
modify
how
you
receive
notifications
at
My
Workspace
>
Preferences.
From
zqian@umich.edu
Fri
Jan
4
10:17:43
2008
Return-Path:
<postmaster@collab.sakaiproject.org>
Received:
from
murder
(mail.umich.edu
[141.211.14.97])
by
frankenstein.mail.umich.edu
(Cyrus
v2.3.8)
with
LMTPA;
Fri,
04
Jan
2008
10:17:43
-0500
X-Sieve:
CMU
Sieve
2.3
Received:
from
murder
([unix
socket])
by
mail.umich.edu
(Cyrus
v2.2.12)
with
LMTPA;
Fri,
04
Jan
2008
10:17:42
-0500
Received:
from
creepshow.mr.itd.umich.edu
(creepshow.mr.itd.umich.edu
[141.211.14.84])
by
sleepers.mail.umich.edu
()
with
ESMTP
id
m04FHgfs011536;
Fri,
4
Jan
2008
10:17:42
-0500
Received:
FROM
paploo.uhi.ac.uk
(app1.prod.collab.uhi.ac.uk
[194.35.219.184])
BY
creepshow.mr.itd.umich.edu
ID
477E4E0F.CCA4B.926
;
4
Jan
2008
10:17:38
-0500
Received:
from
paploo.uhi.ac.uk
(localhost
[127.0.0.1])
by
paploo.uhi.ac.uk
(Postfix)
with
ESMTP
id
BD02DBAC64;
Fri,
4
Jan
2008
15:17:34
+0000
(GMT)
Message-ID:
<200801041515.m04FFv42007050@nakamura.uits.iupui.edu>
Mime-Version:
1.0
Content-Transfer-Encoding:
7bit
Received:
from
prod.collab.uhi.ac.uk
([194.35.219.182])
by
paploo.uhi.ac.uk
(JAMES
SMTP
Server
2.1.3)
with
SMTP
ID
25
for
<source@collab.sakaiproject.org>;
Fri,
4
Jan
2008
15:17:11
+0000
(GMT)
Received:
from
nakamura.uits.iupui.edu
(nakamura.uits.iupui.edu
[134.68.220.122])
by
shmi.uhi.ac.uk
(Postfix)
with
ESMTP
id
5B396236B9
for
<source@collab.sakaiproject.org>;
Fri,
4
Jan
2008
15:17:08
+0000
(GMT)
Received:
from
nakamura.uits.iupui.edu
(localhost
[127.0.0.1])
by
nakamura.uits.iupui.edu
(8.12.11.20060308/8.12.11)
with
ESMTP
id
m04FFv85007052
for
<source@collab.sakaiproject.org>;
Fri,
4
Jan
2008
10:15:57
-0500
Received:
(from
apache@localhost)
by
nakamura.uits.iupui.edu
(8.12.11.20060308/8.12.11/Submit)
id
m04FFv42007050
for
source@collab.sakaiproject.org;
Fri,
4
Jan
2008
10:15:57
-0500
Date:
Fri,
4
Jan
2008
10:15:57
-0500
X-Authentication-Warning:
nakamura.uits.iupui.edu:
apache
set
sender
to
zqian@umich.edu
using
-f
To:
source@collab.sakaiproject.org
From:
zqian@umich.edu
Subject:
[sakai]
svn
commit:
r39757
-
in
assignment/trunk:
assignment-impl/impl/src/java/org/sakaiproject/assignment/impl
assignment-tool/tool/src/webapp/vm/assignment
X-Content-Type-Outer-Envelope:
text/plain;
charset=UTF-8
X-Content-Type-Message-Body:
text/plain;
charset=UTF-8
Content-Type:
text/plain;
charset=UTF-8
X-DSPAM-Result:
Innocent
X-DSPAM-Processed:
Fri
Jan
4
10:17:42
2008
X-DSPAM-Confidence:
0.7605
X-DSPAM-Probability:
0.0000
Details:
http://source.sakaiproject.org/viewsvn/?view=rev&rev=39757
Author:
zqian@umich.edu
Date:
2008-01-04
10:15:54
-0500
(Fri,
04
Jan
2008)
New
Revision:
39757
Modified:
assignment/trunk/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/BaseAssignmentService.java
assignment/trunk/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
Log:
fix
to
SAK-12604:Don't
show
groups/sections
filter
if
the
site
doesn't
have
any
----------------------
This
automatic
notification
message
was
sent
by
Sakai
Collab
(https://collab.sakaiproject.org/portal)
from
the
Source
site.
You
can
modify
how
you
receive
notifications
at
My
Workspace
>
Preferences.
From
antranig@caret.cam.ac.uk
Fri
Jan
4
10:04:14
2008
Return-Path:
<postmaster@collab.sakaiproject.org>
Received:
from
murder
(mail.umich.edu
[141.211.14.25])
by
frankenstein.mail.umich.edu
(Cyrus
v2.3.8)
with
LMTPA;
Fri,
04
Jan
2008
10:04:14
-0500
X-Sieve:
CMU
Sieve
2.3
Received:
from
murder
([unix
socket])
by
mail.umich.edu
(Cyrus
v2.2.12)
with
LMTPA;
Fri,
04
Jan
2008
10:04:14
-0500
Received:
from
holes.mr.itd.umich.edu
(holes.mr.itd.umich.edu
[141.211.14.79])
by
panther.mail.umich.edu
()
with
ESMTP
id
m04F4Dci015108;
Fri,
4
Jan
2008
10:04:13
-0500
Received:
FROM
paploo.uhi.ac.uk
(app1.prod.collab.uhi.ac.uk
[194.35.219.184])
BY
holes.mr.itd.umich.edu
ID
477E4AE3.D7AF.31669
;
4
Jan
2008
10:04:05
-0500
Received:
from
paploo.uhi.ac.uk
(localhost
[127.0.0.1])
by
paploo.uhi.ac.uk
(Postfix)
with
ESMTP
id
933E3BAC17;
Fri,
4
Jan
2008
15:04:00
+0000
(GMT)
Message-ID:
<200801041502.m04F21Jo007031@nakamura.uits.iupui.edu>
Mime-Version:
1.0
Content-Transfer-Encoding:
7bit
Received:
from
prod.collab.uhi.ac.uk
([194.35.219.182])
by
paploo.uhi.ac.uk
(JAMES
SMTP
Server
2.1.3)
with
SMTP
ID
32
for
<source@collab.sakaiproject.org>;
Fri,
4
Jan
2008
15:03:15
+0000
(GMT)
Received:
from
nakamura.uits.iupui.edu
(nakamura.uits.iupui.edu
[134.68.220.122])
by
shmi.uhi.ac.uk
(Postfix)
with
ESMTP
id
AC2F6236B9
for
<source@collab.sakaiproject.org>;
Fri,
4
Jan
2008
15:03:12
+0000
(GMT)
Received:
from
nakamura.uits.iupui.edu
(localhost
[127.0.0.1])
by
nakamura.uits.iupui.edu
(8.12.11.20060308/8.12.11)
with
ESMTP
id
m04F21hn007033
for
<source@collab.sakaiproject.org>;
Fri,
4
Jan
2008
10:02:01
-0500
Received:
(from
apache@localhost)
by
nakamura.uits.iupui.edu
(8.12.11.20060308/8.12.11/Submit)
id
m04F21Jo007031
for
source@collab.sakaiproject.org;
Fri,
4
Jan
2008
10:02:01
-0500
Date:
Fri,
4
Jan
2008
10:02:01
-0500
X-Authentication-Warning:
nakamura.uits.iupui.edu:
apache
set
sender
to
antranig@caret.cam.ac.uk
using
-f
To:
source@collab.sakaiproject.org
From:
antranig@caret.cam.ac.uk
Subject:
[sakai]
svn
commit:
r39756
-
in
component/branches/SAK-12166/component-api/component/src/java/org/sakaiproject/component:
impl
impl/spring/support
impl/spring/support/dynamic
impl/support
util
X-Content-Type-Outer-Envelope:
text/plain;
charset=UTF-8
X-Content-Type-Message-Body:
text/plain;
charset=UTF-8
Content-Type:
text/plain;
charset=UTF-8
X-DSPAM-Result:
Innocent
X-DSPAM-Processed:
Fri
Jan
4
10:04:14
2008
X-DSPAM-Confidence:
0.6932
X-DSPAM-Probability:
0.0000
Details:
http://source.sakaiproject.org/viewsvn/?view=rev&rev=39756
Author:
antranig@caret.cam.ac.uk
Date:
2008-01-04
10:01:40
-0500
(Fri,
04
Jan
2008)
New
Revision:
39756
Added:
component/branches/SAK-12166/component-api/component/src/java/org/sakaiproject/component/impl/spring/support/dynamic/
component/branches/SAK-12166/component-api/component/src/java/org/sakaiproject/component/impl/spring/support/dynamic/DynamicComponentManager.java
component/branches/SAK-12166/component-api/component/src/java/org/sakaiproject/component/impl/support/
component/branches/SAK-12166/component-api/component/src/java/org/sakaiproject/component/impl/support/DynamicComponentRecord.java
component/branches/SAK-12166/component-api/component/src/java/org/sakaiproject/component/impl/support/DynamicJARManager.java
component/branches/SAK-12166/component-api/component/src/java/org/sakaiproject/component/impl/support/JARRecord.java
component/branches/SAK-12166/component-api/component/src/java/org/sakaiproject/component/util/ByteToCharBase64.java
component/branches/SAK-12166/component-api/component/src/java/org/sakaiproject/component/util/FileUtil.java
component/branches/SAK-12166/component-api/component/src/java/org/sakaiproject/component/util/RecordFileIO.java
component/branches/SAK-12166/component-api/component/src/java/org/sakaiproject/component/util/RecordReader.java
component/branches/SAK-12166/component-api/component/src/java/org/sakaiproject/component/util/RecordWriter.java
component/branches/SAK-12166/component-api/component/src/java/org/sakaiproject/component/util/StreamDigestor.java
Modified:
component/branches/SAK-12166/component-api/component/src/java/org/sakaiproject/component/impl/spring/support/ComponentsLoaderImpl.java
Log:
Temporary
commit
of
incomplete
work
on
JAR
caching
----------------------
This
automatic
notification
message
was
sent
by
Sakai
Collab
(https://collab.sakaiproject.org/portal)
from
the
Source
site.
You
can
modify
how
you
receive
notifications
at
My
Workspace
>
Preferences.
From
gopal.ramasammycook@gmail.com
Fri
Jan
4
09:05:31
2008
Return-Path:
<postmaster@collab.sakaiproject.org>
Received:
from
murder
(mail.umich.edu
[141.211.14.90])
by
frankenstein.mail.umich.edu
(Cyrus
v2.3.8)
with
LMTPA;
Fri,
04
Jan
2008
09:05:31
-0500
X-Sieve:
CMU
Sieve
2.3
Received:
from
murder
([unix
socket])
by
mail.umich.edu
(Cyrus
v2.2.12)
with
LMTPA;
Fri,
04
Jan
2008
09:05:31
-0500
Received:
from
guys.mr.itd.umich.edu
(guys.mr.itd.umich.edu
[141.211.14.76])
by
flawless.mail.umich.edu
()
with
ESMTP
id
m04E5U3C029277;
Fri,
4
Jan
2008
09:05:30
-0500
Received:
FROM
paploo.uhi.ac.uk
(app1.prod.collab.uhi.ac.uk
[194.35.219.184])
BY
guys.mr.itd.umich.edu
ID
477E3D23.EE2E7.5237
;
4
Jan
2008
09:05:26
-0500
Received:
from
paploo.uhi.ac.uk
(localhost
[127.0.0.1])
by
paploo.uhi.ac.uk
(Postfix)
with
ESMTP
id
33C7856DC0;
Fri,
4
Jan
2008
14:05:26
+0000
(GMT)
Message-ID:
<200801041403.m04E3psW006926@nakamura.uits.iupui.edu>
Mime-Version:
1.0
Content-Transfer-Encoding:
7bit
Received:
from
prod.collab.uhi.ac.uk
([194.35.219.182])
by
paploo.uhi.ac.uk
(JAMES
SMTP
Server
2.1.3)
with
SMTP
ID
575
for
<source@collab.sakaiproject.org>;
Fri,
4
Jan
2008
14:05:04
+0000
(GMT)
Received:
from
nakamura.uits.iupui.edu
(nakamura.uits.iupui.edu
[134.68.220.122])
by
shmi.uhi.ac.uk
(Postfix)
with
ESMTP
id
3C0261D617
for
<source@collab.sakaiproject.org>;
Fri,
4
Jan
2008
14:05:03
+0000
(GMT)
Received:
from
nakamura.uits.iupui.edu
(localhost
[127.0.0.1])
by
nakamura.uits.iupui.edu
(8.12.11.20060308/8.12.11)
with
ESMTP
id
m04E3pQS006928
for
<source@collab.sakaiproject.org>;
Fri,
4
Jan
2008
09:03:52
-0500
Received:
(from
apache@localhost)
by
nakamura.uits.iupui.edu
(8.12.11.20060308/8.12.11/Submit)
id
m04E3psW006926
for
source@collab.sakaiproject.org;
Fri,
4
Jan
2008
09:03:51
-0500
Date:
Fri,
4
Jan
2008
09:03:51
-0500
X-Authentication-Warning:
nakamura.uits.iupui.edu:
apache
set
sender
to
gopal.ramasammycook@gmail.com
using
-f
To:
source@collab.sakaiproject.org
From:
gopal.ramasammycook@gmail.com
Subject:
[sakai]
svn
commit:
r39755
-
in
sam/branches/SAK-12065:
samigo-api/src/java/org/sakaiproject/tool/assessment/shared/api/grading
samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation
samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation
samigo-services/src/java/org/sakaiproject/tool/assessment/facade
samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/ifc
samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/integrated
samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/standalone
samigo-services/src/java/org/sakaiproject/tool/assessment/shared/impl/grading
X-Content-Type-Outer-Envelope:
text/plain;
charset=UTF-8
X-Content-Type-Message-Body:
text/plain;
charset=UTF-8
Content-Type:
text/plain;
charset=UTF-8
X-DSPAM-Result:
Innocent
X-DSPAM-Processed:
Fri
Jan
4
09:05:31
2008
X-DSPAM-Confidence:
0.7558
X-DSPAM-Probability:
0.0000
Details:
http://source.sakaiproject.org/viewsvn/?view=rev&rev=39755
Author:
gopal.ramasammycook@gmail.com
Date:
2008-01-04
09:02:54
-0500
(Fri,
04
Jan
2008)
New
Revision:
39755
Modified:
sam/branches/SAK-12065/samigo-api/src/java/org/sakaiproject/tool/assessment/shared/api/grading/GradingSectionAwareServiceAPI.java
sam/branches/SAK-12065/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java
sam/branches/SAK-12065/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/SubmissionStatusBean.java
sam/branches/SAK-12065/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/TotalScoresBean.java
sam/branches/SAK-12065/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/SubmissionStatusListener.java
sam/branches/SAK-12065/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
sam/branches/SAK-12065/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueriesAPI.java
sam/branches/SAK-12065/samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/ifc/SectionAwareServiceHelper.java
sam/branches/SAK-12065/samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/integrated/SectionAwareServiceHelperImpl.java
sam/branches/SAK-12065/samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/standalone/SectionAwareServiceHelperImpl.java
sam/branches/SAK-12065/samigo-services/src/java/org/sakaiproject/tool/assessment/shared/impl/grading/GradingSectionAwareServiceImpl.java
Log:
SAK-12065
Gopal
-
Samigo
Group
Release.
SubmissionStatus/TotalScores/Questions
View
filter.
----------------------
This
automatic
notification
message
was
sent
by
Sakai
Collab
(https://collab.sakaiproject.org/portal)
from
the
Source
site.
You
can
modify
how
you
receive
notifications
at
My
Workspace
>
Preferences.
From
david.horwitz@uct.ac.za
Fri
Jan
4
07:02:32
2008
Return-Path:

In [ ]:
url = "https://github.com/cookieSensei/NLP/raw/main/resources/mbox-short.txt"

our_file = urllib.request.urlopen(url)

for line in our_file:
    # print(line.decode().rstrip())
    line = line.decode()

    # If the pattern exists in the string specified in the second argument, 
    # then print line
    if re.search("From: ", line):
        print(line)

From: stephen.marquard@uct.ac.za

From: louis@media.berkeley.edu

From: zqian@umich.edu

From: rjlowe@iupui.edu

From: zqian@umich.edu

From: rjlowe@iupui.edu

From: cwen@iupui.edu

From: cwen@iupui.edu

From: gsilver@umich.edu

From: gsilver@umich.edu

From: zqian@umich.edu

From: gsilver@umich.edu

From: wagnermr@iupui.edu

From: zqian@umich.edu

From: antranig@caret.cam.ac.uk

From: gopal.ramasammycook@gmail.com

From: david.horwitz@uct.ac.za

From: david.horwitz@uct.ac.za

From: david.horwitz@uct.ac.za

From: david.horwitz@uct.ac.za

From: stephen.marquard@uct.ac.za

From: louis@media.berkeley.edu

From: louis@media.berkeley.edu

From: ray@media.berkeley.edu

From: cwen@iupui.edu

From: cwen@iupui.edu

From: cwen@iupui.edu

In [ ]:
url = "https://github.com/cookieSensei/NLP/raw/main/resources/mbox-short.txt"

our_file = urllib.request.urlopen(url)

for line in our_file:
    # print(line.decode().rstrip())
    line = line.decode().rstrip()
    if re.search("From: ", line):
        print(line)

From: stephen.marquard@uct.ac.za
From: louis@media.berkeley.edu
From: zqian@umich.edu
From: rjlowe@iupui.edu
From: zqian@umich.edu
From: rjlowe@iupui.edu
From: cwen@iupui.edu
From: cwen@iupui.edu
From: gsilver@umich.edu
From: gsilver@umich.edu
From: zqian@umich.edu
From: gsilver@umich.edu
From: wagnermr@iupui.edu
From: zqian@umich.edu
From: antranig@caret.cam.ac.uk
From: gopal.ramasammycook@gmail.com
From: david.horwitz@uct.ac.za
From: david.horwitz@uct.ac.za
From: david.horwitz@uct.ac.za
From: david.horwitz@uct.ac.za
From: stephen.marquard@uct.ac.za
From: louis@media.berkeley.edu
From: louis@media.berkeley.edu
From: ray@media.berkeley.edu
From: cwen@iupui.edu
From: cwen@iupui.edu
From: cwen@iupui.edu

In [ ]:
url = "https://github.com/cookieSensei/NLP/raw/main/resources/mbox-short.txt"

our_file = urllib.request.urlopen(url)

for line in our_file:
    # print(line.decode().rstrip())
    line = line.decode().rstrip()
    # . matches any character 
    # + repeats a character one or more times
    # * repeats
    if re.search("^Fr..:.+@", line):
        print(line)

From: stephen.marquard@uct.ac.za
From: louis@media.berkeley.edu
From: zqian@umich.edu
From: rjlowe@iupui.edu
From: zqian@umich.edu
From: rjlowe@iupui.edu
From: cwen@iupui.edu
From: cwen@iupui.edu
From: gsilver@umich.edu
From: gsilver@umich.edu
From: zqian@umich.edu
From: gsilver@umich.edu
From: wagnermr@iupui.edu
From: zqian@umich.edu
From: antranig@caret.cam.ac.uk
From: gopal.ramasammycook@gmail.com
From: david.horwitz@uct.ac.za
From: david.horwitz@uct.ac.za
From: david.horwitz@uct.ac.za
From: david.horwitz@uct.ac.za
From: stephen.marquard@uct.ac.za
From: louis@media.berkeley.edu
From: louis@media.berkeley.edu
From: ray@media.berkeley.edu
From: cwen@iupui.edu
From: cwen@iupui.edu
From: cwen@iupui.edu

^         Matches the beginning of a line
$         Mathes the end of the line
.         Matches any character
\s        Matches whitespace
\S        Matches any non-whitespace character
*         Repeats a character zero or more times
*?        Repeats a character zero or more times (non-greedy)
+         Repeats a character one or more times
+?        Repeats a character one or more times (non-greedy)
[aeiou]   Matches a single character in the listed set
[^XYZ]    Matches a single character not in the listed set
[a-z0-9]  The set of characters can include a range
(        Indicates where string extraction is to start
)         Indicates where string extraction is to end

In [ ]:
import re

some_str = "this is a random string"

re.findall("a", some_str)

['a', 'a']

In [ ]:
str1 = "$45,000,67.00%"
pattern = "[0123456789]"

re.findall(pattern, str1)

['4', '5', '0', '0', '0', '6', '7', '0', '0']

In [ ]:
pattern = "[0-9]"

re.findall(pattern, str1)

['4', '5', '0', '0', '0', '6', '7', '0', '0']

In [ ]:
string1 = "@#$@#$ this is ^#$%^ random %$&##&$^& 87647612 some string"
pattern = "[a-z]"
pattern2 = "[a-z]+"
re.findall(pattern2, string1)

['this', 'is', 'random', 'some', 'string']

In [ ]:
string1 = "@#$@#$ aaaaa this is ^#$%^ random %$&##&$^& 87647612 some string"
pattern = "[a-z]"
pattern2 = "a+"

# \ is an escape character
# \n

re.findall(pattern2, string1)

['aaaaa', 'a']

In [ ]:
string1 = "@#$@#$ aaaaa this is ^#$%^ random %$&##&$^& 87647612 some string"
pattern = "[a-z]"
pattern2 = "a+"

# \ is an escape character
# \n

re.findall("[0-9]+", string1)

['87647612']

In [ ]:
import re

string1 = "This is a sample message sent to cookiesensei@sample_email.com from ashish@gmail.com"

our_list = re.findall("\S+@\S+", string1)
print(our_list)

['cookiesensei@sample_email.com', 'ashish@gmail.com']

In [ ]:
some_numbers = "Lets say we have some sample numbers like 34, 534, 23"

# This is what we've been using till now
print(re.findall("[0-9]", some_numbers))

['3', '4', '5', '3', '4', '2', '3']

In [ ]:
# Rather than extracting the numbers, our pattern
# extracted the numeric digits
# So, we'll try another pattern

print(re.findall("[0-9]+", some_numbers))

['34', '534', '23']

In [ ]:
print(re.findall("[have]", some_numbers))

['e', 'a', 'e', 'h', 'a', 'v', 'e', 'e', 'a', 'e', 'e', 'e']

In [ ]:
print(re.findall("have", some_numbers))

['have']

# Greedy matching

In [ ]:
import re
x = 'From: Using the : character'
y = re.findall('^F.+:', x)
print(y)

# Search till the last :

['From: Using the :']

In [ ]:
import re
x = 'From: Using the : character'
y = re.findall('^F.+?:', x)
print(y)

# Search till first encounter of :

['From:']

In [ ]:
x = 'From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008'
y = re.findall('\S+@\S+', x)
print(y)

['stephen.marquard@uct.ac.za']

In [ ]:
x = 'From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008'
y = re.findall('\S+?@\S+?', x)
print(y)

['stephen.marquard@u']

In [ ]:
# start from caret but start sxtraction only from ()
x = 'From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008'
y = re.findall('^From (\S+@\S+)', x)
print(y)

['stephen.marquard@uct.ac.za']

In [ ]:
# [^ ] says: anything but a whitespace, same as \S
# inside the square brackets ^ acts as a "not"
# like [^ ] means: not a whitespace

import re
line = 'From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008'
y = re.findall('[^ ]@([^ ]+)', line)
print(y)

['uct.ac.za']

In [ ]:
# [^ ] says: anything but a whitespace, same as \S
# inside the square brackets ^ acts as a "not"
# like [^ ] means: not a whitespace
# So, [^F] would mean: not F

import re
line = 'From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008'
y = re.findall('[^F]', line)
print(y)

['r', 'o', 'm', ' ', 's', 't', 'e', 'p', 'h', 'e', 'n', '.', 'm', 'a', 'r', 'q', 'u', 'a', 'r', 'd', '@', 'u', 'c', 't', '.', 'a', 'c', '.', 'z', 'a', ' ', 'S', 'a', 't', ' ', 'J', 'a', 'n', ' ', ' ', '5', ' ', '0', '9', ':', '1', '4', ':', '1', '6', ' ', '2', '0', '0', '8']

In [ ]:
import re
line = 'From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008'
y = re.findall('.*@([^ ]+)', line)
print(y)

['uct.ac.za']

In [ ]:
# $ is a special character
# To look for a dollar sign in a string 
# we'd need to use \$
# \ back slash is used to escape characters
# like \n means new line

In [ ]:
import re
x = 'We just recieved $10.00 for cookies'
y = re.findall('\$[0-9.]+', x)
print(y)

['$10.00']

# NLP

In [ ]:
df = pd.read_csv("https://confrecordings.ams3.digitaloceanspaces.com/Reviews.csv")
df

                                              Tweets  Ratings
0                      Hii , This Product is awesome        2
1                      You can definetely give a try        3
2        This one is not good as it is seems on site        1
3                  The quality of this dress is good        5
4                          I like this one very much        1
5  Delivery ..worst in small cities like .. bhopa...        0
6  Nice genuine product with high quality clear s...        4
7                      Customer Service is too worst        1
8  Got this device yesterday.The audio quality is...        3

In [ ]:
str1 = " Hii, This Product is awesome..."

In [ ]:
re.findall("[a-zA-Z]+", str1)

['Hii', 'This', 'Product', 'is', 'awesome']

In [ ]:
str1.split(" ")
# even the commas come in the list

['', 'Hii,', 'This', 'Product', 'is', 'awesome...']

# Using only Language Processing

In [ ]:
url = "https://confrecordings.ams3.digitaloceanspaces.com/Reviews.csv"
df = pd.read_csv(url)


#break into sentences
df["sentence"]=df["Tweets"].str.split(".")
#break into words
df["words"]=df["Tweets"].str.split()
#count frequency
df["Tweets"].str.split(expand=True).stack().value_counts()
#remove stopwords
word_stop=["is","are","you","so","a","in","up","the","as","it","I","can","the","did","an","You","it's","of","from","my","your","very","one"]
df["clean_text"]=df['Tweets'].apply(lambda x: ' '.join([word for word in x.split() if word not in (word_stop)]))
#length of tweets using len()
df['len'] = df['Tweets'].str.len()

df

,Tweets,Ratings,sentence,words,clean_text,len
0,"Hii , This Product is awesome",2,"[Hii , This Product is awesome]","[Hii, ,, This, Product, is, awesome]","Hii , This Product awesome",29
1,You can definetely give a try,3,[You can definetely give a try],"[You, can, definetely, give, a, try]",definetely give try,29
2,This one is not good as it is seems on site,1,[This one is not good as it is seems on site],"[This, one, is, not, good, as, it, is, seems, ...",This not good seems on site,43
3,The quality of this dress is good,5,[The quality of this dress is good],"[The, quality, of, this, dress, is, good]",The quality this dress good,33
4,I like this one very much,1,[I like this one very much],"[I, like, this, one, very, much]",like this much,25
5,Delivery ..worst in small cities like .. bhopa...,0,"[Delivery , , worst in small cities like , , ...","[Delivery, ..worst, in, small, cities, like, ....",Delivery ..worst small cities like .. bhopal o...,57
6,Nice genuine product with high quality clear s...,4,[Nice genuine product with high quality clear ...,"[Nice, genuine, product, with, high, quality, ...",Nice genuine product with high quality clear s...,50
7,Customer Service is too worst,1,[Customer Service is too worst],"[Customer, Service, is, too, worst]",Customer Service too worst,29
8,Got this device yesterday.The audio quality is...,3,"[Got this device yesterday, The audio quality ...","[Got, this, device, yesterday.The, audio, qual...",Got this device yesterday.The audio quality go...,74

# Using Text Pattern (RE) + Language Processing

In [ ]:
def clean_text(list_of_words):
    word_stop=["is","are","you","so","a","in","up","the","as","it","I","can","the","did","an","You","it's","of","from","my","your","very","one"]
    clean_text = []
    for word in list_of_words:
        if word not in word_stop:
            clean_text.append(word)
    return " ".join(clean_text)

url = "https://confrecordings.ams3.digitaloceanspaces.com/Reviews.csv"
df2 = pd.read_csv(url)

df2["words"] = df2["Tweets"].apply(lambda x: re.findall("[a-zA-Z]+", x.lower()))

df2["clean_text"] = df2["words"].apply(lambda x: clean_text(x))

df2["clean_len"] = df2["clean_text"].apply(lambda x: len(x))
df2["original_len"] = df2["Tweets"].apply(lambda x: len(x))
df2

,Tweets,Ratings,words,clean_text,clean_len,original_len
0,"Hii , This Product is awesome",2,"[hii, this, product, is, awesome]",hii this product awesome,24,29
1,You can definetely give a try,3,"[you, can, definetely, give, a, try]",definetely give try,19,29
2,This one is not good as it is seems on site,1,"[this, one, is, not, good, as, it, is, seems, ...",this not good seems on site,27,43
3,The quality of this dress is good,5,"[the, quality, of, this, dress, is, good]",quality this dress good,23,33
4,I like this one very much,1,"[i, like, this, one, very, much]",i like this much,16,25
5,Delivery ..worst in small cities like .. bhopa...,0,"[delivery, worst, in, small, cities, like, bho...",delivery worst small cities like bhopal or indore,49,57
6,Nice genuine product with high quality clear s...,4,"[nice, genuine, product, with, high, quality, ...",nice genuine product with high quality clear s...,50,50
7,Customer Service is too worst,1,"[customer, service, is, too, worst]",customer service too worst,26,29
8,Got this device yesterday.The audio quality is...,3,"[got, this, device, yesterday, the, audio, qua...",got this device yesterday audio quality good b...,64,74

In [ ]:
df["clean_text"].str.split(expand=True).stack().value_counts()

good             4
quality          3
this             3
This             2
not              2
like             2
Hii              1
Nice             1
genuine          1
product          1
with             1
high             1
clear            1
sound            1
Service          1
Customer         1
or               1
too              1
worst            1
Got              1
device           1
yesterday.The    1
audio            1
but              1
indore           1
cities           1
bhopal           1
..               1
Product          1
awesome          1
definetely       1
give             1
try              1
seems            1
on               1
site             1
The              1
dress            1
much             1
Delivery         1
..worst          1
small            1
,                1
design           1
dtype: int64

In [ ]:
df2["clean_text"].str.split(expand=True).stack().value_counts()

this          5
good          4
quality       3
product       2
worst         2
not           2
like          2
hii           1
sound         1
genuine       1
with          1
high          1
clear         1
service       1
customer      1
indore        1
too           1
got           1
device        1
yesterday     1
audio         1
but           1
nice          1
small         1
or            1
bhopal        1
cities        1
delivery      1
much          1
i             1
dress         1
site          1
on            1
seems         1
try           1
give          1
definetely    1
awesome       1
design        1
dtype: int64

In [ ]:
word_counter = {}

for line in df2["clean_text"]:
    for word in line.split(" "):
        word_counter[word] = word_counter.get(word, 0) + 1
        
print(word_counter)


word_frequency = pd.DataFrame()

keys = []
values = []

for k,v in word_counter.items():
    keys.append(k)
    values.append(v)
    
pd.DataFrame({"word":keys, "frequency":values})

{'hii': 1, 'this': 5, 'product': 2, 'awesome': 1, 'definetely': 1, 'give': 1, 'try': 1, 'not': 2, 'good': 4, 'seems': 1, 'on': 1, 'site': 1, 'quality': 3, 'dress': 1, 'i': 1, 'like': 2, 'much': 1, 'delivery': 1, 'worst': 2, 'small': 1, 'cities': 1, 'bhopal': 1, 'or': 1, 'indore': 1, 'nice': 1, 'genuine': 1, 'with': 1, 'high': 1, 'clear': 1, 'sound': 1, 'customer': 1, 'service': 1, 'too': 1, 'got': 1, 'device': 1, 'yesterday': 1, 'audio': 1, 'but': 1, 'design': 1}

          word  frequency
0          hii          1
1         this          5
2      product          2
3      awesome          1
4   definetely          1
5         give          1
6          try          1
7          not          2
8         good          4
9        seems          1
10          on          1
11        site          1
12     quality          3
13       dress          1
14           i          1
15        like          2
16        much          1
17    delivery          1
18       worst          2
19       small          1
20      cities          1
21      bhopal          1
22          or          1
23      indore          1
24        nice          1
25     genuine          1
26        with          1
27        high          1
28       clear          1
29       sound          1
30    customer          1
31     service          1
32         too          1
33         got          1
34      device          1
35   yesterday          1
36       audio          1
37         but          1
38      design          1